In [4]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv("/Users/animeshsingh/Desktop/Datasets/breast_cancer.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [6]:
df = df.drop(columns = ["id","Unnamed: 32"])

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.15)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-0.33263869, -0.77800909, -0.32431141, ..., -0.19950537,
         1.05769741, -0.15023283],
       [-0.44969614, -0.55525676, -0.51284052, ..., -1.3218597 ,
        -1.61788748, -1.23376203],
       [ 0.79225484,  0.06988688,  0.69747491, ..., -0.45714505,
        -0.61782205, -1.34635097],
       ...,
       [ 0.26406879,  1.44472383,  0.16462122, ..., -1.30426554,
        -2.19497442, -1.60720059],
       [ 0.92073253,  0.70940163,  0.94608472, ...,  0.58993687,
         0.26748178, -0.50360604],
       [-0.66097056, -0.38519853, -0.64957592, ..., -0.20256523,
        -0.69815517, -0.35144376]], shape=(483, 30))

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
# numpy to tensors

In [13]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [14]:
# NN

In [15]:
class NN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

    def fwd(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y = torch.sigmoid(z)
        return y

In [16]:
lr = 0.1
epochs = 500

In [17]:
model = NN(X_train)
model.weights

tensor([[0.1688],
        [0.1042],
        [0.8560],
        [0.1344],
        [0.4562],
        [0.1544],
        [0.9976],
        [0.3853],
        [0.6802],
        [0.5934],
        [0.6818],
        [0.7690],
        [0.0402],
        [0.5748],
        [0.2681],
        [0.0791],
        [0.4027],
        [0.6304],
        [0.9034],
        [0.2280],
        [0.6741],
        [0.5989],
        [0.0157],
        [0.9375],
        [0.2483],
        [0.4577],
        [0.1351],
        [0.1778],
        [0.9646],
        [0.4632]], dtype=torch.float64, requires_grad=True)

In [18]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [25]:
for epoch in range(epochs):
    # fwd
    y = model.fwd(X_train)
    y_train = y_train.to(torch.float64)
    y = y.flatten()
    # loss
    bce = nn.BCELoss()
    loss = bce(y, y_train)
    # back
    loss.backward()
    # grad = model.weights.grad
    # update
    with torch.no_grad():
        model.weights -= lr * model.weights.grad
        model.bias -= lr * model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'epoch: {epoch + 1}, loss: {loss.item()}')

epoch: 1, loss: 0.46274975406766133
epoch: 2, loss: 0.4467691657864873
epoch: 3, loss: 0.4313626758717461
epoch: 4, loss: 0.41650910650436773
epoch: 5, loss: 0.4021830269664054
epoch: 6, loss: 0.38835601374903733
epoch: 7, loss: 0.3749986764306566
epoch: 8, loss: 0.3620827423511789
epoch: 9, loss: 0.34958271255125123
epoch: 10, loss: 0.33747688092711586
epoch: 11, loss: 0.32574778053160136
epoch: 12, loss: 0.3143822124717613
epoch: 13, loss: 0.3033710196529821
epoch: 14, loss: 0.2927087151837535
epoch: 15, loss: 0.28239302055769305
epoch: 16, loss: 0.27242432946579753
epoch: 17, loss: 0.26280509194599305
epoch: 18, loss: 0.2535391123572999
epoch: 19, loss: 0.24463076714388773
epoch: 20, loss: 0.2360841709105204
epoch: 21, loss: 0.22790234430545386
epoch: 22, loss: 0.22008645648959718
epoch: 23, loss: 0.2126352212564588
epoch: 24, loss: 0.20554451466652726
epoch: 25, loss: 0.19880725438908176
epoch: 26, loss: 0.1924135429523035
epoch: 27, loss: 0.18635103836662448
epoch: 28, loss: 0.1806054857559283
epoch: 29, loss: 0.1751613292043853
epoch: 30, loss: 0.17000232541616592
epoch: 31, loss: 0.16511209650647368
epoch: 32, loss: 0.16047458193645625
epoch: 33, loss: 0.15607437272906616
epoch: 34, loss: 0.151896929981294
epoch: 35, loss: 0.14792870223697485
epoch: 36, loss: 0.1441571626023143
epoch: 37, loss: 0.1405707879155592
epoch: 38, loss: 0.13715900052846736
epoch: 39, loss: 0.13391208983093345
epoch: 40, loss: 0.13082112664761206
epoch: 41, loss: 0.1278778797384003
epoch: 42, loss: 0.12507474020613016
epoch: 43, loss: 0.12240465680841721
epoch: 44, loss: 0.11986108301623472
epoch: 45, loss: 0.11743793512102255
epoch: 46, loss: 0.11512955968993442
epoch: 47, loss: 0.11293070811142357
epoch: 48, loss: 0.11083651576012402
epoch: 49, loss: 0.10884248334318082
epoch: 50, loss: 0.10694445818407754
epoch: 51, loss: 0.10513861348893822
epoch: 52, loss: 0.10342142398467241
epoch: 53, loss: 0.10178963670746624
epoch: 54, loss: 0.10024023616993077
epoch: 55, loss: 0.0987704036792328
epoch: 56, loss: 0.09737747125052476
epoch: 57, loss: 0.09605887136888094
epoch: 58, loss: 0.09481208475499421
epoch: 59, loss: 0.09363458916876818
epoch: 60, loss: 0.0925238129543894
epoch: 61, loss: 0.09147709727121739
epoch: 62, loss: 0.09049167058502672
epoch: 63, loss: 0.08956463795208443
epoch: 64, loss: 0.08869298603034025
epoch: 65, loss: 0.0878736028876646
epoch: 66, loss: 0.08710330993411705
epoch: 67, loss: 0.08637890204647411
epoch: 68, loss: 0.0856971914021761
epoch: 69, loss: 0.08505505072358274
epoch: 70, loss: 0.08444945240159084
epoch: 71, loss: 0.08387750106764551
epoch: 72, loss: 0.0833364583509148
epoch: 73, loss: 0.08282375958686924
epoch: 74, loss: 0.08233702301775807
epoch: 75, loss: 0.08187405251261178
epoch: 76, loss: 0.08143283506324175
epoch: 77, loss: 0.08101153434345239
epoch: 78, loss: 0.0806084815188027
epoch: 79, loss: 0.08022216432338175
epoch: 80, loss: 0.07985121522334047
epoch: 81, loss: 0.07949439929419899
epoch: 82, loss: 0.07915060226713674
epoch: 83, loss: 0.07881881905598885
epoch: 84, loss: 0.07849814296275101
epoch: 85, loss: 0.07818775567274207
epoch: 86, loss: 0.07788691808724424
epoch: 87, loss: 0.07759496199703025
epoch: 88, loss: 0.07731128257050328
epoch: 89, loss: 0.07703533161157175
epoch: 90, loss: 0.07676661153185459
epoch: 91, loss: 0.07650466997699096
epoch: 92, loss: 0.07624909504590505
epoch: 93, loss: 0.07599951104350118
epoch: 94, loss: 0.07575557471046332
epoch: 95, loss: 0.07551697187791233
epoch: 96, loss: 0.07528341449915803
epoch: 97, loss: 0.07505463801535385
epoch: 98, loss: 0.07483039901631021
epoch: 99, loss: 0.07461047316192951
epoch: 100, loss: 0.07439465333361814
epoch: 101, loss: 0.07418274798858
epoch: 102, loss: 0.07397457969309852
epoch: 103, loss: 0.07376998381377434
epoch: 104, loss: 0.07356880734823086
epoch: 105, loss: 0.07337090787904794
epoch: 106, loss: 0.07317615263666567
epoch: 107, loss: 0.0729844176587414
epoch: 108, loss: 0.0727955870349699
epoch: 109, loss: 0.07260955222771352
epoch: 110, loss: 0.07242621145995916
epoch: 111, loss: 0.07224546916314097
epoch: 112, loss: 0.07206723547826294
epoch: 113, loss: 0.07189142580453602
epoch: 114, loss: 0.07171796039042873
epoch: 115, loss: 0.07154676396262794
epoch: 116, loss: 0.07137776538892969
epoch: 117, loss: 0.07121089737153909
epoch: 118, loss: 0.07104609616765936
epoch: 119, loss: 0.07088330133460367
epoch: 120, loss: 0.07072245549697254
epoch: 121, loss: 0.0705635041337123
epoch: 122, loss: 0.07040639538310997
epoch: 123, loss: 0.07025107986399017
epoch: 124, loss: 0.07009751051156769
epoch: 125, loss: 0.06994564242657195
epoch: 126, loss: 0.06979543273640683
epoch: 127, loss: 0.06964684046723685
epoch: 128, loss: 0.06949982642600545
epoch: 129, loss: 0.06935435309149246
epoch: 130, loss: 0.06921038451360755
epoch: 131, loss: 0.06906788622019663
epoch: 132, loss: 0.06892682513070958
epoch: 133, loss: 0.06878716947614107
epoch: 134, loss: 0.06864888872471302
epoch: 135, loss: 0.06851195351281829
epoch: 136, loss: 0.06837633558078984
epoch: 137, loss: 0.0682420077131011
epoch: 138, loss: 0.06810894368263937
epoch: 139, loss: 0.06797711819872632
epoch: 140, loss: 0.06784650685859037
epoch: 141, loss: 0.06771708610202078
epoch: 142, loss: 0.06758883316895808
epoch: 143, loss: 0.06746172605979654
epoch: 144, loss: 0.06733574349819438
epoch: 145, loss: 0.06721086489620381
epoch: 146, loss: 0.06708707032155063
epoch: 147, loss: 0.06696434046690548
epoch: 148, loss: 0.06684265662100383
epoch: 149, loss: 0.0667220006414819
epoch: 150, loss: 0.066602354929308
epoch: 151, loss: 0.0664837024046973
epoch: 152, loss: 0.06636602648440763
epoch: 153, loss: 0.06624931106032196
epoch: 154, loss: 0.0661335404792303
epoch: 155, loss: 0.06601869952373085
epoch: 156, loss: 0.06590477339417602
epoch: 157, loss: 0.0657917476915951
epoch: 158, loss: 0.06567960840152993
epoch: 159, loss: 0.06556834187872496
epoch: 160, loss: 0.06545793483261758
epoch: 161, loss: 0.06534837431357801
epoch: 162, loss: 0.06523964769985229
epoch: 163, loss: 0.06513174268516504
epoch: 164, loss: 0.06502464726694139
epoch: 165, loss: 0.0649183497351111
epoch: 166, loss: 0.06481283866145938
epoch: 167, loss: 0.06470810288949293
epoch: 168, loss: 0.06460413152478978
epoch: 169, loss: 0.06450091392580586
epoch: 170, loss: 0.0643984396951114
epoch: 171, loss: 0.06429669867103284
epoch: 172, loss: 0.06419568091967726
epoch: 173, loss: 0.06409537672731806
epoch: 174, loss: 0.06399577659312172
epoch: 175, loss: 0.06389687122219706
epoch: 176, loss: 0.06379865151894931
epoch: 177, loss: 0.06370110858072263
epoch: 178, loss: 0.06360423369171585
epoch: 179, loss: 0.06350801831715655
epoch: 180, loss: 0.06341245409772046
epoch: 181, loss: 0.06331753284418304
epoch: 182, loss: 0.06322324653229149
epoch: 183, loss: 0.06312958729784587
epoch: 184, loss: 0.06303654743197887
epoch: 185, loss: 0.06294411937662407
epoch: 186, loss: 0.06285229572016353
epoch: 187, loss: 0.06276106919324596
epoch: 188, loss: 0.06267043266476673
epoch: 189, loss: 0.06258037913800243
epoch: 190, loss: 0.06249090174689221
epoch: 191, loss: 0.06240199375245905
epoch: 192, loss: 0.06231364853936449
epoch: 193, loss: 0.06222585961259026
epoch: 194, loss: 0.06213862059424139
epoch: 195, loss: 0.062051925220464786
epoch: 196, loss: 0.061965767338478424
epoch: 197, loss: 0.061880140903705784
epoch: 198, loss: 0.061795039977011156
epoch: 199, loss: 0.06171045872203113
epoch: 200, loss: 0.06162639140259824
epoch: 201, loss: 0.06154283238025245
epoch: 202, loss: 0.06145977611183699
epoch: 203, loss: 0.06137721714717478
epoch: 204, loss: 0.06129515012682207
epoch: 205, loss: 0.06121356977989591
epoch: 206, loss: 0.06113247092197263
epoch: 207, loss: 0.06105184845305411
epoch: 208, loss: 0.060971697355599215
epoch: 209, loss: 0.06089201269261776
epoch: 210, loss: 0.060812789605824216
epoch: 211, loss: 0.06073402331384932
epoch: 212, loss: 0.06065570911050655
epoch: 213, loss: 0.06057784236311193
epoch: 214, loss: 0.060500418510854775
epoch: 215, loss: 0.0604234330632174
epoch: 216, loss: 0.060346881598442106
epoch: 217, loss: 0.06027075976204328
epoch: 218, loss: 0.06019506326536333
epoch: 219, loss: 0.06011978788417055
epoch: 220, loss: 0.060044929457297294
epoch: 221, loss: 0.0599704838853172
epoch: 222, loss: 0.059896447129259844
epoch: 223, loss: 0.05982281520936161
epoch: 224, loss: 0.059749584203851236
epoch: 225, loss: 0.05967675024776909
epoch: 226, loss: 0.05960430953181879
epoch: 227, loss: 0.05953225830125006
epoch: 228, loss: 0.059460592854771656
epoch: 229, loss: 0.059389309543493606
epoch: 230, loss: 0.05931840476989732
epoch: 231, loss: 0.05924787498683308
epoch: 232, loss: 0.059177716696543495
epoch: 233, loss: 0.05910792644971255
epoch: 234, loss: 0.05903850084453893
epoch: 235, loss: 0.05896943652583321
epoch: 236, loss: 0.05890073018413786
epoch: 237, loss: 0.05883237855486937
epoch: 238, loss: 0.058764378417481895
epoch: 239, loss: 0.05869672659465161
epoch: 240, loss: 0.05862941995148116
epoch: 241, loss: 0.05856245539472353
epoch: 242, loss: 0.05849582987202485
epoch: 243, loss: 0.05842954037118531
epoch: 244, loss: 0.058363583919437835
epoch: 245, loss: 0.05829795758274396
epoch: 246, loss: 0.05823265846510622
epoch: 247, loss: 0.05816768370789668
epoch: 248, loss: 0.05810303048920113
epoch: 249, loss: 0.05803869602317848
epoch: 250, loss: 0.05797467755943468
epoch: 251, loss: 0.05791097238241118
epoch: 252, loss: 0.05784757781078699
epoch: 253, loss: 0.05778449119689444
epoch: 254, loss: 0.05772170992614783
epoch: 255, loss: 0.0576592314164849
epoch: 256, loss: 0.05759705311782048
epoch: 257, loss: 0.05753517251151229
epoch: 258, loss: 0.05747358710983835
epoch: 259, loss: 0.0574122944554856
epoch: 260, loss: 0.05735129212104968
epoch: 261, loss: 0.05729057770854533
epoch: 262, loss: 0.057230148848927236
epoch: 263, loss: 0.05717000320162101
epoch: 264, loss: 0.05711013845406402
epoch: 265, loss: 0.057050552321255825
epoch: 266, loss: 0.056991242545317934
epoch: 267, loss: 0.05693220689506266
epoch: 268, loss: 0.056873443165570955
epoch: 269, loss: 0.05681494917777855
epoch: 270, loss: 0.05675672277807088
epoch: 271, loss: 0.05669876183788593
epoch: 272, loss: 0.05664106425332513
epoch: 273, loss: 0.05658362794477214
epoch: 274, loss: 0.05652645085651894
epoch: 275, loss: 0.05646953095639957
epoch: 276, loss: 0.05641286623543097
epoch: 277, loss: 0.0563564547074608
epoch: 278, loss: 0.056300294408822144
epoch: 279, loss: 0.05624438339799496
epoch: 280, loss: 0.056188719755273876
epoch: 281, loss: 0.05613330158244258
epoch: 282, loss: 0.056078127002454216
epoch: 283, loss: 0.056023194159117905
epoch: 284, loss: 0.05596850121679123
epoch: 285, loss: 0.055914046360078434
epoch: 286, loss: 0.055859827793534295
epoch: 287, loss: 0.05580584374137343
epoch: 288, loss: 0.05575209244718508
epoch: 289, loss: 0.05569857217365311
epoch: 290, loss: 0.055645281202281065
epoch: 291, loss: 0.055592217833122376
epoch: 292, loss: 0.05553938038451536
epoch: 293, loss: 0.05548676719282309
epoch: 294, loss: 0.055434376612177795
epoch: 295, loss: 0.05538220701423006
epoch: 296, loss: 0.05533025678790236
epoch: 297, loss: 0.05527852433914691
epoch: 298, loss: 0.05522700809070799
epoch: 299, loss: 0.055175706481888284
epoch: 300, loss: 0.055124617968319335
epoch: 301, loss: 0.05507374102173614
epoch: 302, loss: 0.05502307412975547
epoch: 303, loss: 0.05497261579565813
epoch: 304, loss: 0.054922364538175006
epoch: 305, loss: 0.054872318891276715
epoch: 306, loss: 0.054822477403966834
epoch: 307, loss: 0.054772838640078696
epoch: 308, loss: 0.05472340117807568
epoch: 309, loss: 0.054674163610854705
epoch: 310, loss: 0.05462512454555321
epoch: 311, loss: 0.05457628260335926
epoch: 312, loss: 0.05452763641932485
epoch: 313, loss: 0.054479184642182314
epoch: 314, loss: 0.054430925934163744
epoch: 315, loss: 0.0543828589708235
epoch: 316, loss: 0.05433498244086341
epoch: 317, loss: 0.054287295045961095
epoch: 318, loss: 0.054239795500600894
epoch: 319, loss: 0.05419248253190765
epoch: 320, loss: 0.05414535487948311
epoch: 321, loss: 0.054098411295245
epoch: 322, loss: 0.05405165054326875
epoch: 323, loss: 0.054005071399631586
epoch: 324, loss: 0.053958672652259294
epoch: 325, loss: 0.05391245310077529
epoch: 326, loss: 0.053866411556352134
epoch: 327, loss: 0.05382054684156539
epoch: 328, loss: 0.05377485779024977
epoch: 329, loss: 0.053729343247357564
epoch: 330, loss: 0.05368400206881919
epoch: 331, loss: 0.053638833121406035
epoch: 332, loss: 0.053593835282595384
epoch: 333, loss: 0.05354900744043736
epoch: 334, loss: 0.05350434849342403
epoch: 335, loss: 0.0534598573503605
epoch: 336, loss: 0.05341553293023779
epoch: 337, loss: 0.05337137416210806
epoch: 338, loss: 0.05332737998496131
epoch: 339, loss: 0.05328354934760416
epoch: 340, loss: 0.05323988120854043
epoch: 341, loss: 0.05319637453585358
epoch: 342, loss: 0.053153028307090774
epoch: 343, loss: 0.053109841509148784
epoch: 344, loss: 0.05306681313816157
epoch: 345, loss: 0.05302394219938954
epoch: 346, loss: 0.05298122770711045
epoch: 347, loss: 0.052938668684511914
epoch: 348, loss: 0.052896264163585435
epoch: 349, loss: 0.05285401318502217
epoch: 350, loss: 0.05281191479811001
epoch: 351, loss: 0.052769968060632305
epoch: 352, loss: 0.05272817203876799
epoch: 353, loss: 0.05268652580699324
epoch: 354, loss: 0.05264502844798443
epoch: 355, loss: 0.05260367905252267
epoch: 356, loss: 0.05256247671939947
epoch: 357, loss: 0.052521420555323946
epoch: 358, loss: 0.05248050967483145
epoch: 359, loss: 0.0524397432001931
epoch: 360, loss: 0.05239912026132709
epoch: 361, loss: 0.05235863999571089
epoch: 362, loss: 0.052318301548294824
epoch: 363, loss: 0.05227810407141694
epoch: 364, loss: 0.052238046724718955
epoch: 365, loss: 0.05219812867506343
epoch: 366, loss: 0.052158349096452075
epoch: 367, loss: 0.05211870716994528
epoch: 368, loss: 0.052079202083582625
epoch: 369, loss: 0.05203983303230467
epoch: 370, loss: 0.052000599217875636
epoch: 371, loss: 0.05196149984880728
epoch: 372, loss: 0.051922534140283805
epoch: 373, loss: 0.05188370131408775
epoch: 374, loss: 0.05184500059852693
epoch: 375, loss: 0.05180643122836235
epoch: 376, loss: 0.05176799244473716
epoch: 377, loss: 0.05172968349510652
epoch: 378, loss: 0.051691503633168344
epoch: 379, loss: 0.05165345211879518
epoch: 380, loss: 0.051615528217966826
epoch: 381, loss: 0.05157773120270391
epoch: 382, loss: 0.05154006035100242
epoch: 383, loss: 0.05150251494676894
epoch: 384, loss: 0.051465094279757005
epoch: 385, loss: 0.05142779764550404
epoch: 386, loss: 0.05139062434526935
epoch: 387, loss: 0.05135357368597275
epoch: 388, loss: 0.05131664498013418
epoch: 389, loss: 0.051279837545813944
epoch: 390, loss: 0.051243150706553865
epoch: 391, loss: 0.05120658379131916
epoch: 392, loss: 0.051170136134441074
epoch: 393, loss: 0.05113380707556024
epoch: 394, loss: 0.05109759595957081
epoch: 395, loss: 0.05106150213656535
epoch: 396, loss: 0.05102552496178032
epoch: 397, loss: 0.050989663795542435
epoch: 398, loss: 0.050953918003215436
epoch: 399, loss: 0.050918286955148
epoch: 400, loss: 0.05088277002662178
epoch: 401, loss: 0.05084736659780054
epoch: 402, loss: 0.050812076053679725
epoch: 403, loss: 0.05077689778403667
epoch: 404, loss: 0.050741831183381596
epoch: 405, loss: 0.05070687565090901
epoch: 406, loss: 0.050672030590449925
epoch: 407, loss: 0.05063729541042451
epoch: 408, loss: 0.050602669523795454
epoch: 409, loss: 0.0505681523480219
epoch: 410, loss: 0.05053374330501387
epoch: 411, loss: 0.05049944182108733
epoch: 412, loss: 0.050465247326919864
epoch: 413, loss: 0.05043115925750675
epoch: 414, loss: 0.050397177052117756
epoch: 415, loss: 0.050363300154254304
epoch: 416, loss: 0.050329528011607276
epoch: 417, loss: 0.050295860076015345
epoch: 418, loss: 0.050262295803423694
epoch: 419, loss: 0.050228834653843424
epoch: 420, loss: 0.05019547609131127
epoch: 421, loss: 0.05016221958384995
epoch: 422, loss: 0.050129064603428954
epoch: 423, loss: 0.05009601062592572
epoch: 424, loss: 0.0500630571310875
epoch: 425, loss: 0.050030203602493405
epoch: 426, loss: 0.04999744952751719
epoch: 427, loss: 0.049964794397290194
epoch: 428, loss: 0.04993223770666501
epoch: 429, loss: 0.04989977895417943
epoch: 430, loss: 0.049867417642020795
epoch: 431, loss: 0.049835153275990904
epoch: 432, loss: 0.049802985365471196
epoch: 433, loss: 0.04977091342338849
epoch: 434, loss: 0.04973893696618099
epoch: 435, loss: 0.049707055513764746
epoch: 436, loss: 0.049675268589500644
epoch: 437, loss: 0.04964357572016149
epoch: 438, loss: 0.04961197643589981
epoch: 439, loss: 0.04958047027021577
epoch: 440, loss: 0.04954905675992562
epoch: 441, loss: 0.04951773544513043
epoch: 442, loss: 0.049486505869185286
epoch: 443, loss: 0.049455367578668696
epoch: 444, loss: 0.049424320123352496
epoch: 445, loss: 0.049393363056172
epoch: 446, loss: 0.04936249593319656
epoch: 447, loss: 0.04933171831360048
epoch: 448, loss: 0.04930102975963412
epoch: 449, loss: 0.04927042983659558
epoch: 450, loss: 0.04923991811280246
epoch: 451, loss: 0.049209494159564104
epoch: 452, loss: 0.049179157551154096
epoch: 453, loss: 0.049148907864783056
epoch: 454, loss: 0.04911874468057184
epoch: 455, loss: 0.04908866758152489
epoch: 456, loss: 0.049058676153504045
epoch: 457, loss: 0.049028769985202524
epoch: 458, loss: 0.04899894866811925
epoch: 459, loss: 0.048969211796533504
epoch: 460, loss: 0.04893955896747982
epoch: 461, loss: 0.048909989780723105
epoch: 462, loss: 0.04888050383873417
epoch: 463, loss: 0.04885110074666544
epoch: 464, loss: 0.04882178011232692
epoch: 465, loss: 0.0487925415461625
epoch: 466, loss: 0.04876338466122652
epoch: 467, loss: 0.04873430907316045
epoch: 468, loss: 0.04870531440017006
epoch: 469, loss: 0.04867640026300269
epoch: 470, loss: 0.04864756628492471
epoch: 471, loss: 0.04861881209169947
epoch: 472, loss: 0.0485901373115652
epoch: 473, loss: 0.04856154157521338
epoch: 474, loss: 0.048533024515767235
epoch: 475, loss: 0.04850458576876046
epoch: 476, loss: 0.04847622497211626
epoch: 477, loss: 0.04844794176612648
epoch: 478, loss: 0.048419735793431125
epoch: 479, loss: 0.04839160669899797
epoch: 480, loss: 0.048363554130102425
epoch: 481, loss: 0.048335577736307686
epoch: 482, loss: 0.04830767716944501
epoch: 483, loss: 0.0482798520835942
epoch: 484, loss: 0.04825210213506438
epoch: 485, loss: 0.04822442698237497
epoch: 486, loss: 0.04819682628623667
epoch: 487, loss: 0.04816929970953301
epoch: 488, loss: 0.04814184691730166
epoch: 489, loss: 0.04811446757671635
epoch: 490, loss: 0.04808716135706871
epoch: 491, loss: 0.04805992792975036
epoch: 492, loss: 0.04803276696823528
epoch: 493, loss: 0.04800567814806227
epoch: 494, loss: 0.047978661146817585
epoch: 495, loss: 0.047951715644117876
epoch: 496, loss: 0.04792484132159314
epoch: 497, loss: 0.04789803786287
epoch: 498, loss: 0.04787130495355503
epoch: 499, loss: 0.04784464228121836
epoch: 500, loss: 0.04781804953537738

In [26]:
with torch.no_grad():
    y = model.fwd(X_test)
    y = (y > 0.5).float()

accuracy = (y == y_test).float().mean()
accuracy

tensor(0.5189)

# Using NN module and more

In [27]:
class NN1(nn.Module):
    # def __init__(self,n):
    #     super().__init__()
    #     self.linear1 = nn.Linear(n, 3)
    #     self.relu = nn.ReLU()
    #     self.linear2 = nn.Linear(3,1)
    #     self.sigmoid = nn.Sigmoid()

    # def fwd(self, X):
    #     out = self.linear1(X)
    #     out = self.relu(out)
    #     out = self.linear2(out)
    #     out = self.sigmoid(out)
    #     return out

    def __init__(self, n):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n, 50),
            nn.ReLU(),
            nn.Linear(50,10),
            nn.ReLU(),
            nn.Linear(10,1),
            nn.Sigmoid()
        )
    
    def forward(self, vars):
        out = self.net(vars)
        return out

In [28]:
# !pip install torchinfo
X_train = X_train.float()
y_train = y_train.float()

In [29]:
model = NN1(30)
optimizer = torch.optim.SGD(model.parameters(), lr = lr)

for epoch in range(epochs):
    # fwd
    y = model(X_train)
    y = y.flatten()
    
    # loss
    bce = nn.BCELoss()
    loss = bce(y, y_train)
    
    # back
    optimizer.zero_grad()
    loss.backward()
    
    # grad = model.weights.grad
    # update
    optimizer.step()

    print(f'epoch: {epoch + 1}, loss: {loss.item()}')

epoch: 1, loss: 0.6912309527397156
epoch: 2, loss: 0.6804588437080383
epoch: 3, loss: 0.6705710887908936
epoch: 4, loss: 0.6612938046455383
epoch: 5, loss: 0.6524397730827332
epoch: 6, loss: 0.6437876224517822
epoch: 7, loss: 0.6351721286773682
epoch: 8, loss: 0.6264617443084717
epoch: 9, loss: 0.6174744963645935
epoch: 10, loss: 0.6079574227333069
epoch: 11, loss: 0.5978975892066956
epoch: 12, loss: 0.5872682929039001
epoch: 13, loss: 0.5760455131530762
epoch: 14, loss: 0.5643482208251953
epoch: 15, loss: 0.5521063804626465
epoch: 16, loss: 0.5392526984214783
epoch: 17, loss: 0.5258521437644958
epoch: 18, loss: 0.5120048522949219
epoch: 19, loss: 0.4976442754268646
epoch: 20, loss: 0.48285406827926636
epoch: 21, loss: 0.4676997661590576
epoch: 22, loss: 0.4522111117839813
epoch: 23, loss: 0.4364490509033203
epoch: 24, loss: 0.4204796552658081
epoch: 25, loss: 0.40440699458122253
epoch: 26, loss: 0.3883374035358429
epoch: 27, loss: 0.37235161662101746
epoch: 28, loss: 0.3565962314605713
epoch: 29, loss: 0.34118449687957764
epoch: 30, loss: 0.3262149691581726
epoch: 31, loss: 0.31176841259002686
epoch: 32, loss: 0.2979159951210022
epoch: 33, loss: 0.2847293019294739
epoch: 34, loss: 0.27223414182662964
epoch: 35, loss: 0.26044097542762756
epoch: 36, loss: 0.24934642016887665
epoch: 37, loss: 0.2389209121465683
epoch: 38, loss: 0.2291577011346817
epoch: 39, loss: 0.22002826631069183
epoch: 40, loss: 0.21149206161499023
epoch: 41, loss: 0.20351123809814453
epoch: 42, loss: 0.19605542719364166
epoch: 43, loss: 0.18908452987670898
epoch: 44, loss: 0.18257369101047516
epoch: 45, loss: 0.17649084329605103
epoch: 46, loss: 0.1707991361618042
epoch: 47, loss: 0.16546887159347534
epoch: 48, loss: 0.16047121584415436
epoch: 49, loss: 0.15578430891036987
epoch: 50, loss: 0.15138037502765656
epoch: 51, loss: 0.14723904430866241
epoch: 52, loss: 0.14333616197109222
epoch: 53, loss: 0.1396511197090149
epoch: 54, loss: 0.13616661727428436
epoch: 55, loss: 0.13287293910980225
epoch: 56, loss: 0.12975339591503143
epoch: 57, loss: 0.12679536640644073
epoch: 58, loss: 0.12399214506149292
epoch: 59, loss: 0.12132564187049866
epoch: 60, loss: 0.11879022419452667
epoch: 61, loss: 0.11638074368238449
epoch: 62, loss: 0.11408405750989914
epoch: 63, loss: 0.11189045757055283
epoch: 64, loss: 0.10979548841714859
epoch: 65, loss: 0.1077919527888298
epoch: 66, loss: 0.10587484389543533
epoch: 67, loss: 0.1040412038564682
epoch: 68, loss: 0.10228335857391357
epoch: 69, loss: 0.10059497505426407
epoch: 70, loss: 0.09896641969680786
epoch: 71, loss: 0.09739857912063599
epoch: 72, loss: 0.09588933736085892
epoch: 73, loss: 0.09443739056587219
epoch: 74, loss: 0.09304207563400269
epoch: 75, loss: 0.09169595688581467
epoch: 76, loss: 0.09039726108312607
epoch: 77, loss: 0.08914259076118469
epoch: 78, loss: 0.08793249726295471
epoch: 79, loss: 0.0867614597082138
epoch: 80, loss: 0.08562570065259933
epoch: 81, loss: 0.08452673256397247
epoch: 82, loss: 0.08346357941627502
epoch: 83, loss: 0.08243428170681
epoch: 84, loss: 0.0814361646771431
epoch: 85, loss: 0.08046919852495193
epoch: 86, loss: 0.07953125238418579
epoch: 87, loss: 0.07862091064453125
epoch: 88, loss: 0.07773620635271072
epoch: 89, loss: 0.07687616348266602
epoch: 90, loss: 0.07604043185710907
epoch: 91, loss: 0.0752258151769638
epoch: 92, loss: 0.07443299144506454
epoch: 93, loss: 0.07366159558296204
epoch: 94, loss: 0.07291000336408615
epoch: 95, loss: 0.07217665016651154
epoch: 96, loss: 0.07146216183900833
epoch: 97, loss: 0.0707659050822258
epoch: 98, loss: 0.07008790969848633
epoch: 99, loss: 0.06942790001630783
epoch: 100, loss: 0.06878329068422318
epoch: 101, loss: 0.06815330684185028
epoch: 102, loss: 0.06753724068403244
epoch: 103, loss: 0.06693518161773682
epoch: 104, loss: 0.06634682416915894
epoch: 105, loss: 0.06577193737030029
epoch: 106, loss: 0.06520976126194
epoch: 107, loss: 0.0646599531173706
epoch: 108, loss: 0.06412272155284882
epoch: 109, loss: 0.06359701603651047
epoch: 110, loss: 0.06308232992887497
epoch: 111, loss: 0.0625789538025856
epoch: 112, loss: 0.06208677589893341
epoch: 113, loss: 0.061604347079992294
epoch: 114, loss: 0.0611303485929966
epoch: 115, loss: 0.06066553294658661
epoch: 116, loss: 0.060209620743989944
epoch: 117, loss: 0.05976451188325882
epoch: 118, loss: 0.05932788550853729
epoch: 119, loss: 0.0588996559381485
epoch: 120, loss: 0.058479055762290955
epoch: 121, loss: 0.05806663632392883
epoch: 122, loss: 0.05766269937157631
epoch: 123, loss: 0.057265620678663254
epoch: 124, loss: 0.056875649839639664
epoch: 125, loss: 0.05649258941411972
epoch: 126, loss: 0.05611744150519371
epoch: 127, loss: 0.055749811232089996
epoch: 128, loss: 0.05538752302527428
epoch: 129, loss: 0.05503267049789429
epoch: 130, loss: 0.05468297749757767
epoch: 131, loss: 0.05433758720755577
epoch: 132, loss: 0.0540008544921875
epoch: 133, loss: 0.05366610363125801
epoch: 134, loss: 0.053339410573244095
epoch: 135, loss: 0.05301748216152191
epoch: 136, loss: 0.052700579166412354
epoch: 137, loss: 0.0523868203163147
epoch: 138, loss: 0.05208006501197815
epoch: 139, loss: 0.051776207983493805
epoch: 140, loss: 0.05147743225097656
epoch: 141, loss: 0.05118004232645035
epoch: 142, loss: 0.05088847503066063
epoch: 143, loss: 0.050596948713064194
epoch: 144, loss: 0.05031032860279083
epoch: 145, loss: 0.05002373456954956
epoch: 146, loss: 0.04973994195461273
epoch: 147, loss: 0.0494578592479229
epoch: 148, loss: 0.04918258264660835
epoch: 149, loss: 0.04890868067741394
epoch: 150, loss: 0.048641305416822433
epoch: 151, loss: 0.04837362840771675
epoch: 152, loss: 0.048110637813806534
epoch: 153, loss: 0.04784916713833809
epoch: 154, loss: 0.04759057238698006
epoch: 155, loss: 0.04733460769057274
epoch: 156, loss: 0.04708052799105644
epoch: 157, loss: 0.04683194309473038
epoch: 158, loss: 0.04658624157309532
epoch: 159, loss: 0.04634402319788933
epoch: 160, loss: 0.04610631242394447
epoch: 161, loss: 0.04587113857269287
epoch: 162, loss: 0.0456392802298069
epoch: 163, loss: 0.045408304780721664
epoch: 164, loss: 0.045180559158325195
epoch: 165, loss: 0.04495350643992424
epoch: 166, loss: 0.04473003372550011
epoch: 167, loss: 0.04450821876525879
epoch: 168, loss: 0.04428940266370773
epoch: 169, loss: 0.04407298192381859
epoch: 170, loss: 0.043859440833330154
epoch: 171, loss: 0.04364706575870514
epoch: 172, loss: 0.043438494205474854
epoch: 173, loss: 0.04323050379753113
epoch: 174, loss: 0.04302583634853363
epoch: 175, loss: 0.04282302036881447
epoch: 176, loss: 0.04262099042534828
epoch: 177, loss: 0.042425017803907394
epoch: 178, loss: 0.042227860540151596
epoch: 179, loss: 0.04203568026423454
epoch: 180, loss: 0.04184286296367645
epoch: 181, loss: 0.04165402054786682
epoch: 182, loss: 0.04146614670753479
epoch: 183, loss: 0.041279323399066925
epoch: 184, loss: 0.0410948246717453
epoch: 185, loss: 0.040911246091127396
epoch: 186, loss: 0.040729135274887085
epoch: 187, loss: 0.0405501127243042
epoch: 188, loss: 0.040370143949985504
epoch: 189, loss: 0.0401931069791317
epoch: 190, loss: 0.040017642080783844
epoch: 191, loss: 0.03984297439455986
epoch: 192, loss: 0.03967174515128136
epoch: 193, loss: 0.03950079157948494
epoch: 194, loss: 0.039332080632448196
epoch: 195, loss: 0.03916522115468979
epoch: 196, loss: 0.038999978452920914
epoch: 197, loss: 0.03883631154894829
epoch: 198, loss: 0.03867354243993759
epoch: 199, loss: 0.03851412236690521
epoch: 200, loss: 0.03835426643490791
epoch: 201, loss: 0.03819543123245239
epoch: 202, loss: 0.03803878650069237
epoch: 203, loss: 0.037881746888160706
epoch: 204, loss: 0.03772694617509842
epoch: 205, loss: 0.037573058158159256
epoch: 206, loss: 0.037420425564050674
epoch: 207, loss: 0.03726832941174507
epoch: 208, loss: 0.03711818903684616
epoch: 209, loss: 0.03696868568658829
epoch: 210, loss: 0.0368187315762043
epoch: 211, loss: 0.036670222878456116
epoch: 212, loss: 0.036522336304187775
epoch: 213, loss: 0.036376144737005234
epoch: 214, loss: 0.036229584366083145
epoch: 215, loss: 0.03608652576804161
epoch: 216, loss: 0.03594353795051575
epoch: 217, loss: 0.03580174967646599
epoch: 218, loss: 0.03566121309995651
epoch: 219, loss: 0.03552249073982239
epoch: 220, loss: 0.03538377955555916
epoch: 221, loss: 0.03524629771709442
epoch: 222, loss: 0.035109858959913254
epoch: 223, loss: 0.034972354769706726
epoch: 224, loss: 0.034836459904909134
epoch: 225, loss: 0.034701090306043625
epoch: 226, loss: 0.034568432718515396
epoch: 227, loss: 0.0344354473054409
epoch: 228, loss: 0.03430340811610222
epoch: 229, loss: 0.03417211398482323
epoch: 230, loss: 0.03404184803366661
epoch: 231, loss: 0.03391247242689133
epoch: 232, loss: 0.033783264458179474
epoch: 233, loss: 0.033656008541584015
epoch: 234, loss: 0.03352858126163483
epoch: 235, loss: 0.0334024615585804
epoch: 236, loss: 0.03327646106481552
epoch: 237, loss: 0.03315150737762451
epoch: 238, loss: 0.03302803635597229
epoch: 239, loss: 0.03290478512644768
epoch: 240, loss: 0.03278319537639618
epoch: 241, loss: 0.03266284614801407
epoch: 242, loss: 0.03254221752285957
epoch: 243, loss: 0.03242325037717819
epoch: 244, loss: 0.032303981482982635
epoch: 245, loss: 0.03218721225857735
epoch: 246, loss: 0.03206910192966461
epoch: 247, loss: 0.03195219486951828
epoch: 248, loss: 0.03183617442846298
epoch: 249, loss: 0.031720325350761414
epoch: 250, loss: 0.031605761498212814
epoch: 251, loss: 0.03149101138114929
epoch: 252, loss: 0.03137720003724098
epoch: 253, loss: 0.03126520290970802
epoch: 254, loss: 0.03115250915288925
epoch: 255, loss: 0.031040873378515244
epoch: 256, loss: 0.03092929534614086
epoch: 257, loss: 0.030818361788988113
epoch: 258, loss: 0.030709292739629745
epoch: 259, loss: 0.030599486082792282
epoch: 260, loss: 0.030490944162011147
epoch: 261, loss: 0.03038260154426098
epoch: 262, loss: 0.030275247991085052
epoch: 263, loss: 0.03016882948577404
epoch: 264, loss: 0.030062010511755943
epoch: 265, loss: 0.02995624765753746
epoch: 266, loss: 0.029850972816348076
epoch: 267, loss: 0.029746921733021736
epoch: 268, loss: 0.02964281663298607
epoch: 269, loss: 0.02953910082578659
epoch: 270, loss: 0.02943616919219494
epoch: 271, loss: 0.029334502294659615
epoch: 272, loss: 0.0292328093200922
epoch: 273, loss: 0.029131824150681496
epoch: 274, loss: 0.02903091348707676
epoch: 275, loss: 0.02893020771443844
epoch: 276, loss: 0.028831303119659424
epoch: 277, loss: 0.028732258826494217
epoch: 278, loss: 0.028633655980229378
epoch: 279, loss: 0.028535980731248856
epoch: 280, loss: 0.02843807451426983
epoch: 281, loss: 0.02834136039018631
epoch: 282, loss: 0.028244826942682266
epoch: 283, loss: 0.02814842015504837
epoch: 284, loss: 0.02805269882082939
epoch: 285, loss: 0.02795758843421936
epoch: 286, loss: 0.02786312811076641
epoch: 287, loss: 0.027768967673182487
epoch: 288, loss: 0.027675237506628036
epoch: 289, loss: 0.02758200839161873
epoch: 290, loss: 0.027489716187119484
epoch: 291, loss: 0.027398113161325455
epoch: 292, loss: 0.02730635367333889
epoch: 293, loss: 0.02721581794321537
epoch: 294, loss: 0.027125131338834763
epoch: 295, loss: 0.0270350631326437
epoch: 296, loss: 0.026946086436510086
epoch: 297, loss: 0.026856541633605957
epoch: 298, loss: 0.026767738163471222
epoch: 299, loss: 0.026680313050746918
epoch: 300, loss: 0.02659338340163231
epoch: 301, loss: 0.02650744467973709
epoch: 302, loss: 0.026422414928674698
epoch: 303, loss: 0.026337336748838425
epoch: 304, loss: 0.0262525025755167
epoch: 305, loss: 0.026169244199991226
epoch: 306, loss: 0.02608533762395382
epoch: 307, loss: 0.026002127677202225
epoch: 308, loss: 0.025919925421476364
epoch: 309, loss: 0.02583727054297924
epoch: 310, loss: 0.025755692273378372
epoch: 311, loss: 0.025674423202872276
epoch: 312, loss: 0.02559303306043148
epoch: 313, loss: 0.025512052699923515
epoch: 314, loss: 0.025432400405406952
epoch: 315, loss: 0.025353189557790756
epoch: 316, loss: 0.025273803621530533
epoch: 317, loss: 0.02519531548023224
epoch: 318, loss: 0.02511674351990223
epoch: 319, loss: 0.025038395076990128
epoch: 320, loss: 0.0249616838991642
epoch: 321, loss: 0.024884028360247612
epoch: 322, loss: 0.024806812405586243
epoch: 323, loss: 0.02473023533821106
epoch: 324, loss: 0.02465367503464222
epoch: 325, loss: 0.024578025564551353
epoch: 326, loss: 0.024502238258719444
epoch: 327, loss: 0.024426821619272232
epoch: 328, loss: 0.024351486936211586
epoch: 329, loss: 0.024276606738567352
epoch: 330, loss: 0.024202892556786537
epoch: 331, loss: 0.02412838116288185
epoch: 332, loss: 0.02405455708503723
epoch: 333, loss: 0.023981168866157532
epoch: 334, loss: 0.023907728493213654
epoch: 335, loss: 0.023835202679038048
epoch: 336, loss: 0.023762721568346024
epoch: 337, loss: 0.0236903578042984
epoch: 338, loss: 0.0236184261739254
epoch: 339, loss: 0.0235467366874218
epoch: 340, loss: 0.02347581647336483
epoch: 341, loss: 0.023404408246278763
epoch: 342, loss: 0.023333733901381493
epoch: 343, loss: 0.023263288661837578
epoch: 344, loss: 0.02319304831326008
epoch: 345, loss: 0.02312343940138817
epoch: 346, loss: 0.023053834214806557
epoch: 347, loss: 0.022984368726611137
epoch: 348, loss: 0.022915121167898178
epoch: 349, loss: 0.02284621074795723
epoch: 350, loss: 0.022778406739234924
epoch: 351, loss: 0.022710127755999565
epoch: 352, loss: 0.022642388939857483
epoch: 353, loss: 0.02257535420358181
epoch: 354, loss: 0.02250847779214382
epoch: 355, loss: 0.022442134097218513
epoch: 356, loss: 0.022375911474227905
epoch: 357, loss: 0.022310219705104828
epoch: 358, loss: 0.022244304418563843
epoch: 359, loss: 0.02217879332602024
epoch: 360, loss: 0.022113608196377754
epoch: 361, loss: 0.022049076855182648
epoch: 362, loss: 0.02198447287082672
epoch: 363, loss: 0.021919816732406616
epoch: 364, loss: 0.021855687722563744
epoch: 365, loss: 0.021792173385620117
epoch: 366, loss: 0.021728556603193283
epoch: 367, loss: 0.021665718406438828
epoch: 368, loss: 0.021602628752589226
epoch: 369, loss: 0.021539974957704544
epoch: 370, loss: 0.021477436646819115
epoch: 371, loss: 0.021415023133158684
epoch: 372, loss: 0.02135343663394451
epoch: 373, loss: 0.021291883662343025
epoch: 374, loss: 0.021230241283774376
epoch: 375, loss: 0.021168924868106842
epoch: 376, loss: 0.021107833832502365
epoch: 377, loss: 0.021047430112957954
epoch: 378, loss: 0.020986897870898247
epoch: 379, loss: 0.020926566794514656
epoch: 380, loss: 0.020866427570581436
epoch: 381, loss: 0.020806731656193733
epoch: 382, loss: 0.020747486501932144
epoch: 383, loss: 0.020688461139798164
epoch: 384, loss: 0.020630087703466415
epoch: 385, loss: 0.02057158760726452
epoch: 386, loss: 0.020513152703642845
epoch: 387, loss: 0.020455023273825645
epoch: 388, loss: 0.020397065207362175
epoch: 389, loss: 0.020339932292699814
epoch: 390, loss: 0.020282398909330368
epoch: 391, loss: 0.020225342363119125
epoch: 392, loss: 0.020168520510196686
epoch: 393, loss: 0.020111866295337677
epoch: 394, loss: 0.02005556784570217
epoch: 395, loss: 0.019999472424387932
epoch: 396, loss: 0.01994374394416809
epoch: 397, loss: 0.019887739792466164
epoch: 398, loss: 0.01983216591179371
epoch: 399, loss: 0.019776931032538414
epoch: 400, loss: 0.01972304843366146
epoch: 401, loss: 0.01966863125562668
epoch: 402, loss: 0.019614681601524353
epoch: 403, loss: 0.01956132985651493
epoch: 404, loss: 0.01950785517692566
epoch: 405, loss: 0.01945505663752556
epoch: 406, loss: 0.01940208673477173
epoch: 407, loss: 0.019349101930856705
epoch: 408, loss: 0.019296713173389435
epoch: 409, loss: 0.0192439965903759
epoch: 410, loss: 0.01919187419116497
epoch: 411, loss: 0.019139787182211876
epoch: 412, loss: 0.019088076427578926
epoch: 413, loss: 0.01903635822236538
epoch: 414, loss: 0.01898474432528019
epoch: 415, loss: 0.018933573737740517
epoch: 416, loss: 0.01888265274465084
epoch: 417, loss: 0.018831774592399597
epoch: 418, loss: 0.018780989572405815
epoch: 419, loss: 0.01873033680021763
epoch: 420, loss: 0.018680216744542122
epoch: 421, loss: 0.018630046397447586
epoch: 422, loss: 0.01858014054596424
epoch: 423, loss: 0.018530244007706642
epoch: 424, loss: 0.018480774015188217
epoch: 425, loss: 0.01843143440783024
epoch: 426, loss: 0.018382161855697632
epoch: 427, loss: 0.018333379179239273
epoch: 428, loss: 0.01828473061323166
epoch: 429, loss: 0.018236232921481133
epoch: 430, loss: 0.0181877464056015
epoch: 431, loss: 0.018139462918043137
epoch: 432, loss: 0.018091464415192604
epoch: 433, loss: 0.01804351806640625
epoch: 434, loss: 0.01799567975103855
epoch: 435, loss: 0.017948074266314507
epoch: 436, loss: 0.017900850623846054
epoch: 437, loss: 0.017853355035185814
epoch: 438, loss: 0.01780618727207184
epoch: 439, loss: 0.017759358510375023
epoch: 440, loss: 0.01771233044564724
epoch: 441, loss: 0.017665788531303406
epoch: 442, loss: 0.017619213089346886
epoch: 443, loss: 0.017572972923517227
epoch: 444, loss: 0.017526792362332344
epoch: 445, loss: 0.017480840906500816
epoch: 446, loss: 0.01743532344698906
epoch: 447, loss: 0.017389705404639244
epoch: 448, loss: 0.017344549298286438
epoch: 449, loss: 0.017299508675932884
epoch: 450, loss: 0.017254654318094254
epoch: 451, loss: 0.01721019297838211
epoch: 452, loss: 0.01716572418808937
epoch: 453, loss: 0.017121493816375732
epoch: 454, loss: 0.017077576369047165
epoch: 455, loss: 0.017033860087394714
epoch: 456, loss: 0.016990166157484055
epoch: 457, loss: 0.016946759074926376
epoch: 458, loss: 0.016903547570109367
epoch: 459, loss: 0.016860317438840866
epoch: 460, loss: 0.016817262396216393
epoch: 461, loss: 0.016774209216237068
epoch: 462, loss: 0.01673194020986557
epoch: 463, loss: 0.016689296811819077
epoch: 464, loss: 0.01664668880403042
epoch: 465, loss: 0.016604509204626083
epoch: 466, loss: 0.01656264252960682
epoch: 467, loss: 0.01652020774781704
epoch: 468, loss: 0.01647857576608658
epoch: 469, loss: 0.016437049955129623
epoch: 470, loss: 0.01639558933675289
epoch: 471, loss: 0.01635385863482952
epoch: 472, loss: 0.01631208322942257
epoch: 473, loss: 0.016270646825432777
epoch: 474, loss: 0.016228986904025078
epoch: 475, loss: 0.016187813133001328
epoch: 476, loss: 0.016146603971719742
epoch: 477, loss: 0.016105467453598976
epoch: 478, loss: 0.016064612194895744
epoch: 479, loss: 0.016023840755224228
epoch: 480, loss: 0.01598306931555271
epoch: 481, loss: 0.015942677855491638
epoch: 482, loss: 0.015902366489171982
epoch: 483, loss: 0.01586204394698143
epoch: 484, loss: 0.01582210697233677
epoch: 485, loss: 0.015782227739691734
epoch: 486, loss: 0.015742382034659386
epoch: 487, loss: 0.015702668577432632
epoch: 488, loss: 0.01566351391375065
epoch: 489, loss: 0.015623693354427814
epoch: 490, loss: 0.015585695393383503
epoch: 491, loss: 0.015546589158475399
epoch: 492, loss: 0.01550734881311655
epoch: 493, loss: 0.015468735247850418
epoch: 494, loss: 0.015429763123393059
epoch: 495, loss: 0.015391678549349308
epoch: 496, loss: 0.015352696180343628
epoch: 497, loss: 0.01531525794416666
epoch: 498, loss: 0.015276459977030754
epoch: 499, loss: 0.015238874591886997
epoch: 500, loss: 0.015201437287032604

In [33]:
samp = torch.rand(5)
model = NN1(5)
y = model.forward(samp)
y

tensor([0.5113], grad_fn=<SigmoidBackward0>)

In [34]:
samp.shape

torch.Size([5])

In [35]:
y.shape

torch.Size([1])

In [36]:
print(X_train.dtype)

torch.float32

# Dataloader

In [37]:
X_train.shape

torch.Size([483, 30])

In [38]:
y_train.shape

torch.Size([483])

In [39]:
from torch.utils.data import DataLoader, Dataset

In [40]:
class Datalao(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, index):
        return self.X[index], self.y[index]

In [41]:
train_data = Datalao(X_train, y_train)
test_data = Datalao(X_test, y_test)

In [42]:
len(train_data)

483

In [43]:
train_data[0]

(tensor([-0.3326, -0.7780, -0.3243, -0.3950, -0.6885, -0.1753, -0.4994, -0.4635,
         -0.1464, -0.0784, -0.7143, -0.8223, -0.6124, -0.5480, -0.5890, -0.5636,
         -0.5494, -0.6990,  0.0410, -0.7168, -0.3533, -0.6132, -0.2840, -0.4010,
         -0.0477,  0.0243, -0.2974, -0.1995,  1.0577, -0.1502]),
 tensor(0.))

In [44]:
dataloader = DataLoader(train_data, batch_size = 10, shuffle = True, drop_last = False)

In [45]:
for batch_X, batch_y in dataloader:
    print(batch_X)
    print(batch_y)
    print(".."*125)

tensor([[ 1.6402,  0.7142,  1.5925,  1.7588,  0.1312, -0.0307,  0.7365,  1.1926,
         -0.8565, -1.2450,  1.3393, -0.3673,  1.6037,  1.7084, -0.1998, -0.3756,
          0.0536,  0.5455, -0.8606, -0.6766,  2.3017,  0.8956,  2.3783,  2.6641,
          0.8389,  0.4203,  1.2873,  1.9057, -0.2227, -0.4306],
        [-0.0557, -0.7085, -0.1263, -0.1603, -0.6416, -0.9386, -0.9231, -0.7218,
         -1.4290, -0.5672, -0.5633,  0.2731, -0.5869, -0.4514, -0.4846, -1.0019,
         -0.8650, -0.9507, -0.6340, -0.6437, -0.2230,  0.0130, -0.2968, -0.3126,
         -0.7525, -0.9886, -1.0514, -0.8978, -0.8883, -0.7104],
        [ 2.6109,  1.8687,  2.5662,  2.9396, -0.0975,  1.2140,  1.3248,  1.9345,
          0.3282,  0.0244,  2.4713, -0.4663,  2.3371,  2.7311, -0.2217,  0.1772,
          0.4081,  0.8638, -0.5785, -0.2903,  3.0647,  1.5001,  2.9487,  3.6181,
          0.7014,  1.0622,  1.5037,  2.2193,  0.3265,  0.1613],
        [-0.3069, -1.1828, -0.3102, -0.3890, -0.1309, -0.0886, -0.6438, -0.7193,
         -0.6029,  1.3146, -0.8385, -1.0629, -1.0195, -0.6006, -0.6200, -0.1408,
         -0.0355, -0.7429, -0.5195,  0.6784, -0.5104, -1.4308, -0.5748, -0.5194,
         -0.8012, -0.3526, -0.6065, -0.8528, -0.7736,  0.9489],
        [ 0.2127, -1.0702,  0.1282,  0.0903, -0.8341, -1.0290, -0.6840, -0.6048,
         -0.5776, -1.3102, -0.6996, -1.0962, -0.6188, -0.4519, -0.1286, -0.7722,
         -0.5583, -0.2133, -0.5906, -0.7563, -0.1196, -1.3193, -0.1495, -0.1976,
         -0.8145, -0.9866, -0.7750, -0.5307, -0.9342, -1.2516],
        [ 0.2270, -0.5337,  0.1377,  0.0701, -0.5130, -0.6380, -0.6928, -0.5180,
         -0.8891, -0.8172, -0.3802, -1.0127, -0.6533, -0.3765, -0.4453, -0.5055,
         -0.5651, -0.5853, -0.6255, -0.6140,  0.0251, -0.8263, -0.1317, -0.1674,
         -0.4643, -0.6321, -0.7175, -0.5283, -0.6211, -0.8698],
        [-1.0207,  0.0292, -1.0009, -0.9022,  0.2435, -0.3522, -0.7366, -0.9510,
          1.4441,  0.2633, -0.1831,  0.5896, -0.2871, -0.3951,  0.1665, -0.1898,
         -0.1102, -0.5309,  0.7713, -0.1447, -0.9612, -0.3650, -0.9657, -0.8221,
         -0.4599, -0.6742, -0.9210, -1.2578, -0.1276, -0.4657],
        [ 1.5346, -0.0834,  1.5137,  1.4909,  0.8835,  0.7693,  1.7069,  1.8234,
          0.0166, -0.2450,  0.6133,  0.3564,  0.4182,  0.6561, -0.6010,  0.1601,
          0.3309, -0.0175, -0.4255, -0.2325,  1.6069,  0.8140,  1.4011,  1.5144,
          0.8477,  0.7985,  1.5597,  1.4039,  0.5937,  0.3464],
        [ 0.4896,  0.8962,  0.5856,  0.3838,  1.3523,  1.3470,  1.5533,  1.1876,
          1.0057,  1.4438,  0.5608, -0.2655,  0.4007,  0.4414,  0.5338,  0.8115,
          0.8739,  0.3318, -0.6930,  0.7819,  0.8274,  0.8323,  0.7001,  0.6966,
          2.3592,  1.5877,  2.2453,  1.3641,  0.6068,  2.3033],
        [-0.7523, -0.9050, -0.7668, -0.7188, -0.0051, -0.6731, -0.6732, -0.5185,
         -0.3058, -0.5922, -0.8593, -0.4102, -0.9021, -0.6416, -0.6526, -0.5876,
         -0.5737, -0.5329, -0.6858, -0.8262, -0.7999, -0.5799, -0.7961, -0.7186,
         -0.5885, -0.5676, -0.6311, -0.4510, -0.3735, -0.9044]])
tensor([1., 0., 1., 0., 0., 0., 0., 1., 1., 0.])
..........................................................................................................................................................................................................................................................
tensor([[ 1.7401,  0.1178,  1.6380,  1.7991, -1.1552, -0.3548,  0.3319,  0.7347,
          0.3970, -1.6602,  0.7137, -0.9794,  0.5439,  0.8236, -0.8512, -0.6702,
         -0.1855,  0.0984,  0.1482, -0.8258,  1.4208, -0.4117,  1.2912,  1.3693,
         -1.1913, -0.6407, -0.0483,  0.4324,  0.2478, -1.3681],
        [-0.2584,  0.3286, -0.3111, -0.3187, -1.6417, -0.9798, -0.8858, -0.9368,
         -0.3819, -0.5603, -0.3012,  0.4767, -0.2744, -0.3258,  0.2354, -0.2850,
         -0.6035, -1.0287,  0.0193, -0.4191, -0.3491,  0.4926, -0.3399, -0.3931,
         -0.9076, -0.5690, -0.9349, -1.1060, -0.3555, -0.5343],
        [ 0.1556, -0.8331,  0.0461,  0.0448, -1.4407, -1.3142, -0.9299, -0.7764,
         -0.6754, -1.4394, -0.3303, -0.5626, -0.4718, -0.2591, -0.6865, -1.1112,
         -0.8627, -0.9047, -0.6942, -1.0798,  0.0561, -0.6248, -0.0901, -0.0568,
         -1.3819, -1.1855, -1.0775, -0.8584, -0.6129, -1.5007],
        [-1.1880, -0.2654, -1.1174, -0.9993,  0.0375,  0.4767,  0.5217, -0.3012,
         -0.5413,  2.5340,  0.1043,  1.9352,  0.1534, -0.2926,  1.9181,  3.5651,
          2.8036,  2.0780,  2.1815,  5.1482, -1.0191, -0.1852, -0.9999, -0.8441,
         -0.0964,  0.2887,  0.3766, -0.2316, -0.4752,  1.8017],
        [-0.5268,  0.2088, -0.5012, -0.5653,  0.9332,  0.2069, -0.0897, -0.7017,
          1.1072,  0.8368, -0.8397, -0.7765, -0.9856, -0.6437, -0.2736, -0.2018,
          0.2379, -0.3220, -0.9039, -0.0123, -0.6262, -0.2218, -0.6417, -0.6255,
          0.3513, -0.1289,  0.4003, -0.5104, -0.3194,  0.2516],
        [-0.8380,  0.7837, -0.8319, -0.7804, -0.0570, -0.4251, -0.5082, -0.6782,
          0.7666,  0.3619, -0.4663,  0.4656, -0.4505, -0.5195, -1.1975,  0.2843,
          0.0709, -0.2656,  1.0148,  0.3206, -0.8619,  0.4593, -0.8594, -0.7630,
         -1.0450, -0.4795, -0.5514, -0.7666,  0.4347, -0.1982],
        [-0.6438, -0.4259, -0.6753, -0.6350,  0.3010, -0.9253, -0.8168, -0.8601,
         -0.3638, -0.7103, -0.8216,  1.3152, -0.9722, -0.5991,  0.2450, -0.9542,
         -0.5346, -0.9184,  1.2884, -0.6799, -0.7482,  0.1628, -0.8068, -0.6706,
          0.1474, -0.9939, -0.8816, -1.0890,  0.4855, -1.0097],
        [ 0.2669, -0.8762,  0.2438,  0.1012, -0.9058,  0.1005, -0.2982, -0.2847,
          0.2268, -0.5339, -0.6482, -1.3305, -0.3009, -0.4717, -0.9899,  0.3732,
          0.1347, -0.0518, -0.8184, -0.2351,  0.0458, -1.0312,  0.2218, -0.1137,
         -0.8278,  0.7340,  0.3361,  0.3620,  0.0822, -0.0142],
        [ 1.2633, -0.3948,  1.2320,  1.2058,  0.3365,  0.5204,  0.7515,  1.1112,
          0.0492,  0.5632,  1.4681, -0.3155,  1.0656,  1.3166,  0.2926,  0.3772,
          0.3882,  0.6304, -0.5460,  0.5152,  1.3567, -0.4367,  1.1783,  1.2698,
          0.3956,  0.3801,  0.3993,  0.7965, -0.6457,  0.5894],
        [ 0.5724,  0.1154,  0.5193,  0.4849, -0.3397, -0.3814,  0.1094,  0.4537,
         -0.0740, -1.2505,  1.2986, -0.3692,  1.1601,  0.9273,  1.2394, -0.1989,
          0.0885,  1.0156, -0.6267, -0.6945,  0.7406, -0.1569,  0.6555,  0.6110,
          0.7857, -0.3065,  0.0594,  0.5777, -0.4162, -1.1150]])
tensor([1., 0., 0., 0., 0., 0., 0., 0., 1., 1.])
..........................................................................................................................................................................................................................................................
tensor([[-5.3820e-01,  3.2378e-01, -5.9447e-01, -5.4913e-01, -1.1601e+00,
         -1.2149e+00, -8.1303e-01, -8.0400e-01, -2.8772e-01, -8.5333e-01,
         -7.9701e-01,  6.5809e-01, -8.8091e-01, -5.9420e-01, -6.7021e-01,
         -1.1068e+00, -6.9071e-01, -8.2746e-01, -7.5088e-01, -8.4670e-01,
         -5.8900e-01,  1.2220e+00, -6.5801e-01, -5.6872e-01, -8.8544e-01,
         -1.0687e+00, -7.5374e-01, -6.1090e-01, -3.4403e-01, -8.4137e-01],
        [-1.2872e-02, -8.4028e-01, -8.1917e-02, -1.2344e-01, -1.1935e+00,
         -9.2166e-01, -8.5000e-01, -5.7613e-01, -8.3118e-01, -9.7971e-01,
         -7.1470e-01, -1.0375e+00, -6.5644e-01, -4.8651e-01, -7.5105e-01,
         -9.2788e-01, -7.3806e-01, -1.8070e-01, -1.0835e+00, -6.3746e-01,
         -2.6436e-01, -1.0312e+00, -3.0305e-01, -3.2218e-01, -1.2799e+00,
         -9.8268e-01, -1.0044e+00, -4.9080e-01, -1.2588e+00, -9.3501e-01],
        [ 9.8475e-02,  1.3456e-01,  1.8492e-01,  4.7281e-03, -6.3164e-01,
          1.2026e+00,  5.9039e-01,  4.4436e-01, -3.7829e-01,  1.2507e+00,
          1.8034e+00,  1.0264e+00,  8.0503e-01,  8.7688e-01,  2.2206e-01,
          4.6091e+00,  2.1593e+00,  2.5855e+00,  2.4189e+00,  6.9553e+00,
         -8.6538e-02, -5.6155e-01, -1.4948e-01, -1.8519e-01, -1.4382e+00,
         -2.5678e-02, -2.3466e-01, -1.8574e-01, -1.0359e+00,  2.2934e-01],
        [-4.9252e-01,  1.8423e+00, -4.3163e-01, -4.9527e-01,  4.9280e-01,
          5.8880e-01,  2.4444e-01, -8.2679e-02,  4.5139e-01,  8.9656e-01,
          6.8590e-03,  1.0986e+00, -1.0666e-01, -1.2858e-01,  6.6653e-01,
          7.3683e-01,  1.7284e-01,  2.1914e-01, -2.3142e-01,  6.6775e-01,
         -1.1135e-01,  2.3044e+00, -1.4948e-01, -1.8240e-01,  2.0490e+00,
          1.4437e+00,  8.3006e-01,  4.8437e-01,  5.1012e-01,  2.0413e+00],
        [-2.8125e-01, -8.2831e-01, -2.4600e-01, -3.7257e-01,  7.8403e-01,
          4.3108e-01, -5.4014e-01, -4.5781e-01,  5.3834e-01,  7.2157e-01,
         -8.2420e-01, -8.6576e-01, -7.7478e-01, -5.9443e-01, -9.9724e-01,
         -3.7271e-01, -4.8909e-01, -8.7756e-01, -4.7247e-01, -5.2003e-01,
         -3.4914e-01, -8.3466e-01, -3.1612e-01, -4.2422e-01, -4.7674e-02,
          1.7427e-01, -3.9401e-01, -6.3355e-01,  4.5930e-01, -1.1400e-01],
        [-5.1822e-01, -2.9418e-01, -5.5096e-01, -5.4452e-01, -7.0481e-01,
         -7.1302e-01, -6.2544e-01, -6.5906e-01,  5.4921e-01, -8.8101e-02,
         -6.9280e-01, -4.3153e-01, -7.2118e-01, -5.5108e-01, -5.2449e-01,
         -5.6419e-01, -3.9421e-01, -6.4353e-01, -3.2663e-01, -4.9845e-01,
         -5.3731e-01, -4.6980e-02, -5.9801e-01, -5.4006e-01, -4.6878e-01,
         -4.7557e-01, -3.6842e-01, -4.9157e-01,  3.4290e-01, -1.4243e-01],
        [-1.0236e+00, -1.0032e+00, -9.9763e-01, -9.0944e-01,  1.2059e-01,
         -5.7264e-02, -3.1946e-01, -6.8826e-01,  3.8618e-01,  8.6601e-01,
         -2.8652e-01, -1.6371e-01, -1.4806e-01, -4.5070e-01,  8.9649e-02,
          7.4936e-01,  6.5365e-01,  1.2612e-01,  1.0967e-01,  3.5974e-01,
         -8.3920e-01, -6.5481e-01, -7.5217e-01, -7.5637e-01,  1.8815e-02,
          3.1897e-01,  1.1252e-01, -3.2343e-01,  1.9043e-01,  7.0143e-01],
        [-4.9823e-01, -1.6235e+00, -5.2693e-01, -5.3358e-01,  4.5018e-01,
         -6.5563e-01, -6.1271e-01, -3.0538e-01,  5.0936e-01, -4.6725e-01,
         -6.3239e-01, -1.0177e+00, -6.2248e-01, -5.2940e-01,  3.1621e-01,
         -7.8188e-01, -4.9390e-01,  8.8584e-02, -1.7598e-01, -5.8478e-01,
         -5.5592e-01, -1.6423e+00, -5.8702e-01, -5.6645e-01,  2.7591e-01,
         -8.1890e-01, -7.0691e-01, -3.1104e-01, -1.2599e-01, -9.0101e-01],
        [-1.1960e+00,  5.5516e-02, -1.1443e+00, -1.0111e+00,  2.8680e-01,
         -1.3954e-01, -3.4206e-01, -4.7873e-01,  4.5864e-01,  4.2446e-02,
         -8.4270e-01,  1.2127e-02, -6.9783e-01, -6.6277e-01,  6.5322e-01,
         -2.0289e-01, -6.2444e-02, -1.2194e-01, -5.5563e-01, -1.0118e-01,
         -1.1225e+00,  2.2113e-01, -1.0252e+00, -8.9476e-01,  1.0472e+00,
         -1.3749e-01, -2.9927e-02, -2.5627e-01, -4.6207e-01,  5.7109e-02],
        [ 1.4089e+00, -6.1848e-02,  1.3190e+00,  1.4074e+00, -1.0152e+00,
         -4.5668e-01,  4.7231e-02,  1.9247e-01,  4.6226e-01, -1.7324e+00,
          1.0803e+00,  2.3423e-01,  1.2593e+00,  9.7396e-01, -8.8712e-01,
          1.0199e-01,  2.6163e-01,  2.8442e-01, -4.8222e-02, -4.2455e-01,
          1.2678e+00,  3.7950e-02,  1.2318e+00,  1.1614e+00, -1.3376e+00,
         -1.6249e-01,  2.4193e-01,  1.1566e-01, -1.0303e-01, -1.0292e+00]])
tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 1.])
..........................................................................................................................................................................................................................................................
tensor([[-9.2649e-01,  1.2076e+00, -9.3962e-01, -8.2879e-01, -1.0330e+00,
         -7.2765e-01, -9.1732e-01, -1.0505e+00,  5.7095e-01,  5.0779e-02,
          4.3843e-01,  1.3004e+00,  3.8262e-01, -1.6251e-01,  3.8874e-01,
         -3.8867e-01, -6.2404e-01, -9.7107e-01,  4.7727e-01, -3.1810e-01,
         -6.5310e-01,  9.9049e-01, -6.7821e-01, -6.4245e-01, -5.2640e-01,
         -5.7751e-01, -1.0075e+00, -1.2484e+00,  2.5437e-01, -4.2446e-01],
        [ 1.3547e+00,  1.9444e-01,  1.2154e+00,  1.3037e+00, -5.1373e-01,
         -8.6408e-01, -1.0901e-01,  2.4827e-01, -9.7248e-01, -1.7991e+00,
         -2.8388e-01, -7.1713e-01, -2.5472e-01, -7.4384e-02,  1.5852e-01,
         -8.1949e-01, -1.9259e-01,  4.5089e-01, -1.6875e-01, -7.9402e-01,
          7.7985e-01, -2.0019e-01,  6.6145e-01,  6.3375e-01, -3.5353e-01,
         -8.8862e-01, -2.3949e-01,  2.3193e-01, -5.5224e-01, -1.4773e+00],
        [-9.0936e-01, -8.4986e-01, -8.7664e-01, -8.3657e-01,  3.0101e-01,
          4.9146e-02, -4.7183e-01, -8.5541e-01,  1.5430e-01,  7.5768e-01,
         -9.6390e-01, -1.2539e+00, -8.1830e-01, -7.1397e-01, -8.7182e-01,
          3.0828e-01, -1.4963e-01, -8.4476e-01, -1.0341e+00,  3.0194e-01,
         -8.7848e-01, -1.0245e+00, -7.7088e-01, -7.6913e-01,  4.0979e-02,
          9.1225e-01,  3.1822e-01, -5.2905e-01, -5.2929e-01,  1.3446e+00],
        [-7.7232e-01, -3.8280e-01, -7.9045e-01, -7.1877e-01, -5.5990e-01,
         -9.7258e-01, -7.6308e-01, -7.1874e-01, -7.8770e-01, -5.2558e-01,
         -8.0003e-01,  6.2848e-01, -7.8752e-01, -6.1823e-01, -5.6674e-01,
         -8.8748e-01, -6.6058e-01, -9.7842e-01, -8.7864e-01, -8.0024e-01,
         -6.4896e-01,  1.8015e+00, -6.4345e-01, -6.1502e-01,  5.7733e-01,
         -5.8475e-01, -4.3215e-01, -4.1706e-01,  1.1337e-01, -3.5813e-01],
        [-1.5400e+00, -1.1301e+00, -1.5392e+00, -1.2159e+00, -3.6101e-01,
         -1.1696e+00, -1.1107e+00, -1.2613e+00, -3.4931e-01,  6.0075e-01,
         -6.9129e-01, -7.9246e-01, -7.4719e-01, -6.7243e-01,  6.9115e-01,
         -9.9803e-01, -1.0334e+00, -1.9367e+00,  7.7255e-01, -1.6373e-01,
         -1.4322e+00, -1.4092e+00, -1.4368e+00, -1.0730e+00, -7.1257e-01,
         -1.1874e+00, -1.3066e+00, -1.7478e+00, -5.1126e-01, -3.0072e-01],
        [-1.1960e+00, -4.5466e-01, -1.1870e+00, -1.0195e+00,  8.8348e-01,
         -6.0794e-01, -8.9134e-01, -7.5698e-01,  4.1878e-01, -8.9395e-03,
         -7.1659e-01,  2.3423e-01, -7.0367e-01, -6.4957e-01,  8.7313e-01,
         -7.4256e-01, -7.7774e-01, -7.0832e-01,  1.6872e-01, -5.0284e-01,
         -1.1928e+00, -3.8004e-01, -1.1778e+00, -9.4648e-01,  4.0889e-01,
         -8.3140e-01, -1.0066e+00, -8.9287e-01,  1.3960e-01, -5.6157e-01],
        [-5.8103e-01, -2.9658e-01, -6.4129e-01, -5.8571e-01, -1.3945e+00,
         -1.2426e+00, -1.0913e+00, -1.1168e+00, -1.5812e+00, -3.0753e-01,
         -6.4183e-01, -5.6591e-01, -7.3073e-01, -5.4024e-01, -7.8698e-01,
         -1.0619e+00, -9.9542e-01, -1.2919e+00, -7.2798e-01, -7.6512e-01,
         -6.4483e-01, -5.4157e-01, -7.1266e-01, -6.1135e-01, -1.3730e+00,
         -1.1655e+00, -1.2693e+00, -1.3200e+00, -1.2015e+00, -7.5275e-01],
        [-1.2993e-01,  1.3226e+00, -1.5774e-01, -2.2108e-01, -2.7577e-01,
         -4.8823e-01, -4.5059e-01, -4.6427e-01, -2.0801e-01, -2.2420e-01,
         -6.5127e-01, -3.8952e-01, -5.7896e-01, -4.7285e-01, -1.0002e+00,
         -7.8530e-01, -4.5768e-01, -8.1391e-01, -9.0033e-01, -8.7121e-01,
          1.4505e-01,  1.6882e+00,  1.9212e-01, -4.2967e-02,  6.5712e-01,
          2.4531e-01,  5.2633e-01,  2.8548e-01,  9.2818e-01, -2.7174e-01],
        [-1.8090e+00,  1.5142e+00, -1.8060e+00, -1.3553e+00, -1.0997e+00,
         -1.0552e+00, -1.1107e+00, -1.2613e+00,  1.8691e-01,  1.3799e+00,
         -9.7353e-02,  4.5634e-01, -1.8626e-01, -4.8911e-01,  1.8516e+00,
         -9.0201e-01, -1.0334e+00, -1.9367e+00,  9.7865e-01,  1.1067e+00,
         -1.4705e+00,  9.0223e-01, -1.4722e+00, -1.0925e+00, -2.9590e-01,
         -1.1030e+00, -1.3066e+00, -1.7478e+00,  2.5273e-01,  8.6418e-01],
        [ 1.1092e+00,  2.0162e-01,  9.3780e-01,  9.5807e-01, -8.8381e-01,
         -7.0485e-01, -1.9981e-01,  1.8446e-01,  1.1253e+00, -1.7588e+00,
          5.5548e-01, -2.6805e-03,  2.7277e-01,  3.3327e-01, -1.0215e+00,
         -9.7438e-01, -2.9901e-01, -3.2709e-01,  3.5482e+00, -7.1135e-01,
          9.0805e-01,  3.8766e-01,  6.6739e-01,  6.7743e-01, -1.1115e+00,
         -8.6100e-01, -2.2066e-01,  6.5172e-02,  3.2431e+00, -1.2689e+00]])
tensor([0., 1., 0., 0., 0., 0., 0., 1., 0., 1.])
..........................................................................................................................................................................................................................................................
tensor([[-6.9973e-02,  1.2747e+00,  3.1615e-02, -1.5397e-01,  1.4020e+00,
          1.2121e+00,  5.8415e-01,  4.8492e-01,  1.6543e+00,  1.3132e+00,
          2.7041e-01,  5.7850e-01,  6.9520e-02, -1.9952e-02,  8.6015e-01,
          7.4310e-01,  8.0840e-02,  7.0058e-01,  4.3870e-01,  1.1517e+00,
         -3.6912e-02,  1.2386e+00, -2.1748e-02, -1.4903e-01,  2.0889e+00,
          9.5697e-01,  3.2595e-01,  5.7923e-01,  1.2249e+00,  1.9187e+00],
        [-2.8981e-01, -1.3849e-01, -2.6837e-01, -3.9562e-01,  8.3375e-01,
          4.9569e-01,  8.8696e-02,  1.8627e-01,  7.8471e-01,  2.9104e-01,
         -3.5071e-01,  5.4519e-01, -1.3426e-01, -4.3185e-01,  2.3703e-01,
          7.8641e-01,  6.0525e-01,  1.1249e+00,  9.5213e-01,  6.8348e-01,
         -4.1324e-01, -1.0860e-01, -3.7166e-01, -4.9289e-01,  8.9738e-02,
          9.6660e-02, -6.4210e-02,  1.7686e-01,  3.4290e-01, -3.9316e-02],
        [ 9.9211e-01,  3.6354e-02,  9.7509e-01,  8.7051e-01, -4.8177e-01,
          2.9427e-01,  1.8324e-01,  6.7326e-01, -1.1319e+00, -1.1117e+00,
         -2.4103e-02, -7.1676e-01,  1.3002e-01,  1.9635e-02, -3.3419e-01,
          9.6716e-03, -1.6374e-01,  2.5831e-01, -5.7371e-01, -4.3480e-01,
          8.7496e-01,  5.6268e-02,  9.7334e-01,  6.3899e-01,  2.5818e-01,
          5.9785e-01,  3.8727e-01,  1.2187e+00,  3.9598e-02, -2.9013e-01],
        [-5.0109e-01, -6.3430e-01, -5.1284e-01, -5.1399e-01, -3.3686e-01,
         -6.8452e-01, -6.8951e-01, -6.7431e-01, -3.5655e-01, -5.2419e-01,
         -5.7764e-01, -3.5250e-01, -5.8533e-01, -4.7638e-01, -7.4540e-01,
         -4.1773e-01, -4.4806e-01, -6.3684e-01, -8.2440e-01, -5.6429e-01,
         -4.2978e-01, -3.8170e-01, -5.0563e-01, -4.5812e-01, -6.5051e-01,
         -4.3939e-01, -4.8430e-01, -4.2287e-01, -4.6863e-01, -4.3393e-01],
        [-1.3510e+00,  6.6389e-01, -1.3490e+00, -1.1099e+00, -2.8856e-01,
         -9.1710e-01, -6.1158e-01, -9.3008e-01, -4.5800e-01,  3.9520e-01,
         -3.8583e-01,  1.2282e+00, -3.8314e-01, -5.1927e-01,  1.2793e+00,
         -4.0918e-01,  2.4752e-01,  1.5550e-01,  2.0357e+00,  2.8402e-01,
         -1.3117e+00, -7.5289e-02, -1.3032e+00, -1.0090e+00, -9.7410e-01,
         -1.1058e+00, -9.2067e-01, -1.3555e+00, -7.6865e-01, -5.5433e-01],
        [ 4.8962e-01, -3.0616e-01,  4.9859e-01,  3.7915e-01,  4.5295e-02,
          4.7289e-01,  1.3253e-01,  4.4539e-01,  8.5461e-02, -2.9087e-01,
          3.8633e-01, -4.2672e-01,  3.8262e-01,  3.3610e-01, -4.4032e-01,
          8.5992e-01, -1.3873e-01,  1.5550e-01, -7.4737e-02,  1.0880e-01,
          8.7496e-01,  2.9607e-01,  8.8423e-01,  7.4383e-01,  3.2467e-01,
          2.0376e+00,  6.0794e-01,  1.0214e+00,  1.4561e+00,  1.1663e+00],
        [-3.7546e-01, -5.9118e-01, -3.7528e-01, -4.4803e-01,  1.1392e+00,
          1.4035e-01, -6.2607e-01, -4.8752e-01,  1.0927e+00,  4.6048e-01,
         -7.5831e-02, -3.9322e-01, -1.8467e-01, -2.6572e-01,  1.3789e-01,
         -5.6476e-01, -3.9966e-01, -4.3545e-01, -3.1940e-01, -7.9595e-02,
         -3.5948e-01, -6.2650e-01, -3.8919e-01, -4.3540e-01,  6.7485e-01,
         -3.4994e-01, -6.1951e-01, -5.1697e-01,  2.7404e-01,  9.4453e-02],
        [-1.2243e+00, -5.2172e-01, -1.2044e+00, -1.0344e+00,  5.1411e-01,
         -3.8524e-01, -5.6937e-01, -8.0193e-01, -8.4929e-01,  1.0743e+00,
         -1.8254e-03,  3.8601e-01, -5.0943e-02, -4.0121e-01,  2.2475e+00,
          2.1653e-01, -1.6085e-01, -2.6719e-01,  1.4595e+00,  2.8951e-01,
         -1.0625e+00, -6.7146e-01, -1.0412e+00, -8.8462e-01,  6.3938e-01,
         -4.9069e-01, -6.7890e-01, -9.3173e-01, -6.0799e-01,  4.4847e-02],
        [-6.7239e-01, -8.9058e-01, -6.8521e-01, -6.5973e-01,  1.3168e+00,
         -5.9863e-01, -6.1033e-01, -4.2164e-01,  6.9051e-01,  2.9799e-01,

In [46]:
class NN1(nn.Module):
    def __init__(self, n):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n, 50),
            nn.ReLU(),
            nn.Linear(50,10),
            nn.ReLU(),
            nn.Linear(10,1),
            nn.Sigmoid()
        )
    
    def forward(self, vars):
        out = self.net(vars)
        return out

In [47]:
model = NN1(30)
optimizer = torch.optim.SGD(model.parameters(), lr = lr)
epochs = 100
for epoch in range(epochs):
    for batch_X, batch_y in dataloader:
        # fwd
        y = model(batch_X)
        y = y.flatten()
        
        # loss
        bce = nn.BCELoss()
        loss = bce(y, batch_y)
        
        # back
        optimizer.zero_grad()
        loss.backward()
        
        # grad = model.weights.grad
        # update
        optimizer.step()
    
    print(f'epoch: {epoch + 1}, loss: {loss.item()}')

epoch: 1, loss: 0.23425771296024323
epoch: 2, loss: 0.08684676140546799
epoch: 3, loss: 0.07997328788042068
epoch: 4, loss: 0.017640432342886925
epoch: 5, loss: 0.002951130038127303
epoch: 6, loss: 0.005326279904693365
epoch: 7, loss: 0.0230911523103714
epoch: 8, loss: 4.218657340970822e-05
epoch: 9, loss: 0.8055124878883362
epoch: 10, loss: 0.0008612559176981449
epoch: 11, loss: 2.777666668407619e-05
epoch: 12, loss: 0.0006499275332316756
epoch: 13, loss: 0.0005734793958254158
epoch: 14, loss: 0.000333952164510265
epoch: 15, loss: 0.47776177525520325
epoch: 16, loss: 0.00013964319077786058
epoch: 17, loss: 0.00609651580452919
epoch: 18, loss: 0.007417734246701002
epoch: 19, loss: 0.0016035815933719277
epoch: 20, loss: 0.01871153526008129
epoch: 21, loss: 1.0409940841782372e-05
epoch: 22, loss: 0.00010761552402982488
epoch: 23, loss: 0.0002915022778324783
epoch: 24, loss: 0.0003579398326110095
epoch: 25, loss: 0.00020078547822777182
epoch: 26, loss: 9.617943760531489e-06
epoch: 27, loss: 4.795757922693156e-05
epoch: 28, loss: 0.00024944948381744325
epoch: 29, loss: 9.91673514363356e-05
epoch: 30, loss: 0.0004941621446050704
epoch: 31, loss: 2.3829534256947227e-07
epoch: 32, loss: 0.0001258940901607275
epoch: 33, loss: 0.00013419029710348696
epoch: 34, loss: 1.1858496691274922e-05
epoch: 35, loss: 0.00013727828627452254
epoch: 36, loss: 0.002641405677422881
epoch: 37, loss: 1.2937766769027803e-07
epoch: 38, loss: 0.020688533782958984
epoch: 39, loss: 0.00012830457126256078
epoch: 40, loss: 1.348743694506993e-08
epoch: 41, loss: 1.0337046205677325e-06
epoch: 42, loss: 0.0054304953664541245
epoch: 43, loss: 1.4089873729972169e-06
epoch: 44, loss: 0.01068482082337141
epoch: 45, loss: 9.798456449061632e-05
epoch: 46, loss: 0.00046989406109787524
epoch: 47, loss: 0.0002190040104323998
epoch: 48, loss: 1.4064858078199904e-06
epoch: 49, loss: 2.862933797587175e-06
epoch: 50, loss: 6.640193896600977e-05
epoch: 51, loss: 1.9310491552460007e-05
epoch: 52, loss: 0.00012150369730079547
epoch: 53, loss: 1.143578629125841e-05
epoch: 54, loss: 4.0137649648386287e-08
epoch: 55, loss: 0.0024645812809467316
epoch: 56, loss: 7.783967157592997e-05
epoch: 57, loss: 5.1814520702464506e-05
epoch: 58, loss: 1.2747025721182581e-05
epoch: 59, loss: 4.565224198671558e-09
epoch: 60, loss: 3.012740705798933e-07
epoch: 61, loss: 2.2801948489359347e-06
epoch: 62, loss: 6.5962449298240244e-06
epoch: 63, loss: 0.02508655935525894
epoch: 64, loss: 4.904630372948304e-07
epoch: 65, loss: 1.6716343864686678e-08
epoch: 66, loss: 0.0
epoch: 67, loss: 0.00022121024085208774
epoch: 68, loss: 6.659241989837028e-06
epoch: 69, loss: 2.4551499677727406e-07
epoch: 70, loss: 1.3619119272334501e-06
epoch: 71, loss: 1.510457731113135e-10
epoch: 72, loss: 0.0010576385539025068
epoch: 73, loss: 1.6943356229148776e-07
epoch: 74, loss: 9.09302766416431e-09
epoch: 75, loss: 1.571145991086098e-11
epoch: 76, loss: 9.240947110811248e-05
epoch: 77, loss: 0.000866105139721185
epoch: 78, loss: 1.948356612047064e-06
epoch: 79, loss: 0.0005510073387995362
epoch: 80, loss: 2.939225333389514e-14
epoch: 81, loss: 1.239189972856991e-09
epoch: 82, loss: 4.611053761038875e-09
epoch: 83, loss: 0.0005100480047985911
epoch: 84, loss: 9.373255124955904e-06
epoch: 85, loss: 0.0007334074471145868
epoch: 86, loss: 6.1252345841703395e-16
epoch: 87, loss: 6.8630946195233355e-15
epoch: 88, loss: 4.758479462907417e-06
epoch: 89, loss: 1.0530318832024932e-05
epoch: 90, loss: 2.9984096272528404e-06
epoch: 91, loss: 0.00018545375496614724
epoch: 92, loss: 0.002386990003287792
epoch: 93, loss: 7.486398345690759e-08
epoch: 94, loss: 0.0001199624894070439
epoch: 95, loss: 1.2790884795776947e-07
epoch: 96, loss: 2.416815902961389e-07
epoch: 97, loss: 5.802091254736297e-05
epoch: 98, loss: 1.6294151783671301e-16
epoch: 99, loss: 9.511466600997665e-07
epoch: 100, loss: 9.183143265545368e-05

# ANN

In [48]:
df2 = pd.read_csv("/Users/animeshsingh/Desktop/Datasets/Fashion_MNIST/fashion-mnist_train.csv")
df2.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [49]:
X = df2.iloc[:,1:].values
y = df2.iloc[:,0].values

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 40, test_size = 0.2)

In [51]:
X_train = X_train/255.0
X_test = X_test/255.0

In [52]:
X_train.dtype

dtype('float64')

In [53]:
class Datass(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype = torch.float32)
        self.y = torch.tensor(y, dtype = torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [54]:
train = Datass(X_train, y_train)

In [55]:
len(train)

48000

In [56]:
test = Datass(X_test, y_test)

In [57]:
len(test)

12000

In [58]:
train_load = DataLoader(train, batch_size = 1200, num_workers = 0, shuffle = True, pin_memory = True)
test_load = DataLoader(test, batch_size = 1200, shuffle = False, pin_memory = True)

In [59]:
class ANN(nn.Module):
    def __init__(self, n):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, X):
        return self.net(X)

In [60]:
lr = 0.01
epochs = 200

In [61]:
net = ANN(X_train.shape[1])
# device = 'mps'
# net = net.to(device)
crit = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(net.parameters(), lr = lr, weight_decay = 0.0001)

In [62]:
net.parameters

<bound method Module.parameters of ANN(
  (net): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=64, bias=True)
    (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=64, out_features=10, bias=True)
  )
)>

In [63]:
for epoch in range(epochs):
    for batch_X, batch_y in train_load:
        #data to gpu
        # batch_X = batch_X.to(device)
        # batch_y = batch_y.to(device)

        #fwd
        y = net(batch_X)
        
        #loss
        loss = crit(y, batch_y)
        #back
        optimizer.zero_grad()
        loss.backward()
        #update param
        optimizer.step()
    print(f'epoch: {epoch + 1}, loss is:  {loss}')

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

epoch: 1, loss is:  1.3048208951950073
epoch: 2, loss is:  1.0512317419052124
epoch: 3, loss is:  0.919634997844696
epoch: 4, loss is:  0.8234858512878418
epoch: 5, loss is:  0.7354304790496826
epoch: 6, loss is:  0.6906117796897888
epoch: 7, loss is:  0.6402059197425842
epoch: 8, loss is:  0.6152352690696716
epoch: 9, loss is:  0.6263336539268494
epoch: 10, loss is:  0.5585490465164185
epoch: 11, loss is:  0.5450193285942078
epoch: 12, loss is:  0.526728093624115
epoch: 13, loss is:  0.5092233419418335
epoch: 14, loss is:  0.4816353917121887
epoch: 15, loss is:  0.4960978329181671
epoch: 16, loss is:  0.49509790539741516
epoch: 17, loss is:  0.46825718879699707
epoch: 18, loss is:  0.4441409707069397
epoch: 19, loss is:  0.45402657985687256
epoch: 20, loss is:  0.40447884798049927
epoch: 21, loss is:  0.40315955877304077
epoch: 22, loss is:  0.43916183710098267
epoch: 23, loss is:  0.4179874062538147
epoch: 24, loss is:  0.4159972369670868
epoch: 25, loss is:  0.3996221125125885
epoch: 26, loss is:  0.4039899706840515
epoch: 27, loss is:  0.4037157893180847
epoch: 28, loss is:  0.3907397985458374
epoch: 29, loss is:  0.39346301555633545
epoch: 30, loss is:  0.38428375124931335
epoch: 31, loss is:  0.3936837315559387
epoch: 32, loss is:  0.3798522353172302
epoch: 33, loss is:  0.3477524220943451
epoch: 34, loss is:  0.39785531163215637
epoch: 35, loss is:  0.3549794554710388
epoch: 36, loss is:  0.3692932426929474
epoch: 37, loss is:  0.37161579728126526
epoch: 38, loss is:  0.3371967673301697
epoch: 39, loss is:  0.33573734760284424
epoch: 40, loss is:  0.32994839549064636
epoch: 41, loss is:  0.34918832778930664
epoch: 42, loss is:  0.36376985907554626
epoch: 43, loss is:  0.35262611508369446
epoch: 44, loss is:  0.30353277921676636
epoch: 45, loss is:  0.352206826210022
epoch: 46, loss is:  0.3304987847805023
epoch: 47, loss is:  0.30980148911476135
epoch: 48, loss is:  0.3503522574901581
epoch: 49, loss is:  0.35857686400413513
epoch: 50, loss is:  0.34588128328323364
epoch: 51, loss is:  0.3122941851615906
epoch: 52, loss is:  0.3094870448112488
epoch: 53, loss is:  0.31393393874168396
epoch: 54, loss is:  0.2946814298629761
epoch: 55, loss is:  0.2678476870059967
epoch: 56, loss is:  0.2958548069000244
epoch: 57, loss is:  0.28348633646965027
epoch: 58, loss is:  0.28064045310020447
epoch: 59, loss is:  0.2876538336277008
epoch: 60, loss is:  0.29646217823028564
epoch: 61, loss is:  0.28042739629745483
epoch: 62, loss is:  0.2961280345916748
epoch: 63, loss is:  0.2987073063850403
epoch: 64, loss is:  0.2565661370754242
epoch: 65, loss is:  0.31786203384399414
epoch: 66, loss is:  0.2673369348049164
epoch: 67, loss is:  0.2756951153278351
epoch: 68, loss is:  0.26105189323425293
epoch: 69, loss is:  0.2456594854593277
epoch: 70, loss is:  0.2940647304058075
epoch: 71, loss is:  0.27623841166496277
epoch: 72, loss is:  0.3354659974575043
epoch: 73, loss is:  0.245570570230484
epoch: 74, loss is:  0.27527865767478943
epoch: 75, loss is:  0.2535359263420105
epoch: 76, loss is:  0.2748778760433197
epoch: 77, loss is:  0.24696101248264313
epoch: 78, loss is:  0.2575891315937042
epoch: 79, loss is:  0.26861485838890076
epoch: 80, loss is:  0.2490214854478836
epoch: 81, loss is:  0.2508341372013092
epoch: 82, loss is:  0.27616697549819946
epoch: 83, loss is:  0.23642598092556
epoch: 84, loss is:  0.2593180537223816
epoch: 85, loss is:  0.2570376396179199
epoch: 86, loss is:  0.22399485111236572
epoch: 87, loss is:  0.23438629508018494
epoch: 88, loss is:  0.2359018176794052
epoch: 89, loss is:  0.2390427440404892
epoch: 90, loss is:  0.2596966326236725
epoch: 91, loss is:  0.2380581647157669
epoch: 92, loss is:  0.254337340593338
epoch: 93, loss is:  0.25084131956100464
epoch: 94, loss is:  0.2168508619070053
epoch: 95, loss is:  0.2131139487028122
epoch: 96, loss is:  0.214653879404068
epoch: 97, loss is:  0.2158540040254593
epoch: 98, loss is:  0.22244171798229218
epoch: 99, loss is:  0.2222410887479782
epoch: 100, loss is:  0.22968123853206635
epoch: 101, loss is:  0.21074853837490082
epoch: 102, loss is:  0.26016002893447876
epoch: 103, loss is:  0.18751730024814606
epoch: 104, loss is:  0.22886250913143158
epoch: 105, loss is:  0.199254110455513
epoch: 106, loss is:  0.22191965579986572
epoch: 107, loss is:  0.16535231471061707
epoch: 108, loss is:  0.2176901251077652
epoch: 109, loss is:  0.212055504322052
epoch: 110, loss is:  0.20464128255844116
epoch: 111, loss is:  0.22005276381969452
epoch: 112, loss is:  0.22972168028354645
epoch: 113, loss is:  0.21653592586517334
epoch: 114, loss is:  0.21333225071430206
epoch: 115, loss is:  0.23396243155002594
epoch: 116, loss is:  0.22108876705169678
epoch: 117, loss is:  0.1844799965620041
epoch: 118, loss is:  0.20644313097000122
epoch: 119, loss is:  0.19923284649848938
epoch: 120, loss is:  0.19449327886104584
epoch: 121, loss is:  0.200825035572052
epoch: 122, loss is:  0.1852264702320099
epoch: 123, loss is:  0.1716383695602417
epoch: 124, loss is:  0.1878158003091812
epoch: 125, loss is:  0.2253878265619278
epoch: 126, loss is:  0.19135445356369019
epoch: 127, loss is:  0.20037555694580078
epoch: 128, loss is:  0.20683762431144714
epoch: 129, loss is:  0.19925270974636078
epoch: 130, loss is:  0.17160163819789886
epoch: 131, loss is:  0.1738029271364212
epoch: 132, loss is:  0.19171199202537537
epoch: 133, loss is:  0.2043692022562027
epoch: 134, loss is:  0.2126423716545105
epoch: 135, loss is:  0.16843850910663605
epoch: 136, loss is:  0.18466845154762268
epoch: 137, loss is:  0.16055770218372345
epoch: 138, loss is:  0.1952236145734787
epoch: 139, loss is:  0.1801603138446808
epoch: 140, loss is:  0.15932944416999817
epoch: 141, loss is:  0.17790746688842773
epoch: 142, loss is:  0.1945255994796753
epoch: 143, loss is:  0.1690557450056076
epoch: 144, loss is:  0.18334949016571045
epoch: 145, loss is:  0.16636472940444946
epoch: 146, loss is:  0.16754381358623505
epoch: 147, loss is:  0.15280160307884216
epoch: 148, loss is:  0.15031853318214417
epoch: 149, loss is:  0.1892961710691452
epoch: 150, loss is:  0.18662166595458984
epoch: 151, loss is:  0.1483786255121231
epoch: 152, loss is:  0.14890432357788086
epoch: 153, loss is:  0.17483466863632202
epoch: 154, loss is:  0.18161940574645996
epoch: 155, loss is:  0.1642453372478485
epoch: 156, loss is:  0.15551961958408356
epoch: 157, loss is:  0.18188202381134033
epoch: 158, loss is:  0.18264524638652802
epoch: 159, loss is:  0.16832667589187622
epoch: 160, loss is:  0.1385534107685089
epoch: 161, loss is:  0.15613526105880737
epoch: 162, loss is:  0.1491396576166153
epoch: 163, loss is:  0.16858325898647308
epoch: 164, loss is:  0.159782275557518
epoch: 165, loss is:  0.13748139142990112
epoch: 166, loss is:  0.14579391479492188
epoch: 167, loss is:  0.1550816148519516
epoch: 168, loss is:  0.17546850442886353
epoch: 169, loss is:  0.1386115700006485
epoch: 170, loss is:  0.14514277875423431
epoch: 171, loss is:  0.16231532394886017
epoch: 172, loss is:  0.14981889724731445
epoch: 173, loss is:  0.12925978004932404
epoch: 174, loss is:  0.16271086037158966
epoch: 175, loss is:  0.14343243837356567
epoch: 176, loss is:  0.1244347020983696
epoch: 177, loss is:  0.12705069780349731
epoch: 178, loss is:  0.138891339302063
epoch: 179, loss is:  0.13857004046440125
epoch: 180, loss is:  0.13311265408992767
epoch: 181, loss is:  0.129268079996109
epoch: 182, loss is:  0.14546814560890198
epoch: 183, loss is:  0.11221468448638916
epoch: 184, loss is:  0.13219569623470306
epoch: 185, loss is:  0.12008120119571686
epoch: 186, loss is:  0.10402752459049225
epoch: 187, loss is:  0.13579235970973969
epoch: 188, loss is:  0.1251746267080307
epoch: 189, loss is:  0.13500791788101196
epoch: 190, loss is:  0.17346838116645813
epoch: 191, loss is:  0.13504908978939056
epoch: 192, loss is:  0.11532419919967651
epoch: 193, loss is:  0.1188400536775589
epoch: 194, loss is:  0.12363895773887634
epoch: 195, loss is:  0.10776757448911667
epoch: 196, loss is:  0.13186609745025635
epoch: 197, loss is:  0.1237771213054657
epoch: 198, loss is:  0.12256243079900742
epoch: 199, loss is:  0.13111935555934906
epoch: 200, loss is:  0.11569437384605408

In [64]:
net.eval()

ANN(
  (net): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=64, bias=True)
    (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=64, out_features=10, bias=True)
  )
)

In [67]:
# device = torch.device('mps')
with torch.no_grad():
    total_loss = 0
    for batch_X, batch_y in test_load:
        # batch_X = batch_X.to(device)
        # batch_y = batch_y.to(device)
        y = net(batch_X)
        loss = crit(y, batch_y)
        total_loss += loss
avg_loss = total_loss / (len(test_load))
print(avg_loss)

tensor(0.4224)

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)

In [69]:
df2['label'].value_counts()

label
2    6000
9    6000
6    6000
0    6000
3    6000
4    6000
5    6000
8    6000
7    6000
1    6000
Name: count, dtype: int64

# Hyperparameter tuning (Optuna)

In [85]:
class NNH(nn.Module):
    def __init__(self, input_dim, output_dim, num_hidden, neurons):
        super().__init__()

        layers = []
        for i in range(num_hidden):
            layers.append(nn.Linear(input_dim, neurons))
            layers.append(nn.BatchNorm1d(neurons))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(0.2))
            input_dim = neurons
        layers.append(nn.Linear(neurons, output_dim))

        self.model = nn.Sequential(*layers)

    def forward(self, X):
        return self.model(X)

In [100]:
def obj(trial):
    
    # next hyperparams
    num_hidden = trial.suggest_int("num_hidden", 1, 5)
    neurons = trial.suggest_int("num_neurons", 8, 128, step = 8)
    # model init
    input_dim = 784
    output_dim = 10

    model = NNH(input_dim, output_dim, num_hidden, neurons)
    
    # params init
    lr = 0.1
    epochs = 100
    # optim selection
    crit = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters())
    # train loop
    for epoch in range(epochs):
        for batch_X, batch_y in train_load:
            #data to gpu
            # batch_X = batch_X.to(device)
            # batch_y = batch_y.to(device)
    
            #fwd
            y = net(batch_X)
            
            #loss
            loss = crit(y, batch_y)
            #back
            optimizer.zero_grad()
            loss.backward()
            #update param
            optimizer.step()

    # eval
    model.eval()
    total = 0
    correct = 0
    with torch.no_grad():
        for batch_X, batch_y in test_load:
            outputs = model(batch_X)
            _, predicted = torch.max(outputs, 1)
            total = total + batch_y.shape[0]
            correct = correct + (predicted == batch_y).sum().item()
            accuracy = correct / total
    
    return accuracy

In [101]:
import optuna

study = optuna.create_study(direction = "maximize")

[I 2026-06-06 14:13:27,331] A new study created in memory with name: no-name-7dbf0be5-fab3-4a05-bfb0-d26ccea5da9f

In [102]:
study.optimize(obj, n_trials = 10)

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
[I 2026-06-06 14:13:40,750] Trial 0 finished with value: 0.09891666666666667 and parameters: {'num_hidden': 5, 'num_neurons': 72}. Best is trial 0 with value: 0.09891666666666667.
[I 2026-06-06 14:13:53,662] Trial 1 finished with value: 0.09816666666666667 and parameters: {'num_hidden': 5, 'num_neurons': 48}. Best is trial 0 with value: 0.09891666666666667.
[I 2026-06-06 14:14:06,594] Trial 2 finished with value: 0.10316666666666667 and parameters: {'num_hidden': 1, 'num_neurons': 48}. Best is trial 2 with value: 0.10316666666666667.
[I 2026-06-06 14:14:19,645] Trial 3 finished with value: 0.09816666666666667 and parameters: {'num_hidden': 5, 'num_neurons': 48}. Best is trial 2 with value: 0.10316666666666667.
[I 2026-06-06 14:14:32,776] Trial 4 finished with value: 0.10225 and parameters: {'num_hidden': 3, 'num_neurons': 32}. Best is trial 2 with value: 0.10316666666666667.
[I 2026-06-06 14:14:45,936] Trial 5 finished with value: 0.10333333333333333 and parameters: {'num_hidden': 5, 'num_neurons': 32}. Best is trial 5 with value: 0.10333333333333333.
[I 2026-06-06 14:14:59,194] Trial 6 finished with value: 0.10233333333333333 and parameters: {'num_hidden': 3, 'num_neurons': 112}. Best is trial 5 with value: 0.10333333333333333.
[I 2026-06-06 14:15:12,732] Trial 7 finished with value: 0.10766666666666666 and parameters: {'num_hidden': 1, 'num_neurons': 88}. Best is trial 7 with value: 0.10766666666666666.
[I 2026-06-06 14:15:26,214] Trial 8 finished with value: 0.07891666666666666 and parameters: {'num_hidden': 1, 'num_neurons': 64}. Best is trial 7 with value: 0.10766666666666666.
[I 2026-06-06 14:15:39,592] Trial 9 finished with value: 0.10166666666666667 and parameters: {'num_hidden': 5, 'num_neurons': 32}. Best is trial 7 with value: 0.10766666666666666.